// ===== PitchIQ — app.js =====
// Data last updated: Mar 16, 2026 — Sources: NBC Sports, BBC Sport, The Athletic, Sky Sports, Wikipedia, Marca, AS, Kicker, Bundesliga.com, Fabrizio Romano

// ─── DATA ────────────────────────────────────────────────────────────────────

// League mapping helper
const CLUB_LEAGUE_MAP = {
  // Premier League
  'Liverpool': 'premier-league', 'Tottenham': 'premier-league', 'Chelsea': 'premier-league',
  'Arsenal': 'premier-league', 'Man City': 'premier-league', 'Man United': 'premier-league',
  'Newcastle': 'premier-league', 'Everton': 'premier-league', 'West Ham': 'premier-league',
  'Sunderland': 'premier-league', 'Bournemouth': 'premier-league', 'Brighton': 'premier-league',
  'Wolves': 'premier-league', 'Fulham': 'premier-league', 'Brentford': 'premier-league',
  'Aston Villa': 'premier-league', 'Crystal Palace': 'premier-league', 'Nottm Forest': 'premier-league',
  'Burnley': 'premier-league', 'Leeds': 'premier-league',
  // La Liga
  'Real Madrid': 'la-liga', 'Barcelona': 'la-liga', 'Atletico Madrid': 'la-liga',
  'Valencia': 'la-liga', 'Sevilla': 'la-liga', 'Villarreal': 'la-liga',
  // Bundesliga
  'Bayern Munich': 'bundesliga', 'Dortmund': 'bundesliga', 'Leipzig': 'bundesliga',
  'Leverkusen': 'bundesliga', 'Frankfurt': 'bundesliga',
};

// INJURIES & SUSPENSIONS — Real EPL GW30 data (Mar 14–15, 2026)
const INJURIES_DATA = [
  {
    type: 'injury',
    player: 'Alexander Isak',
    avatar: '🧑',
    club: 'Liverpool',
    league: 'premier-league',
    clubBadge: '❤️',
    position: 'ST',
    detail: 'Broken leg — OUT for the remainder of the 2025-26 season. The £125m summer signing from Newcastle has barely featured since arriving at Anfield. Surgery was successful but Slot confirmed he will not return this campaign.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  {
    type: 'injury',
    player: 'James Maddison',
    avatar: '🧑',
    club: 'Tottenham',
    league: 'premier-league',
    clubBadge: '⚪',
    position: 'CAM',
    detail: 'Torn ACL — season over. Carried off in tears earlier in the campaign. One of 13 Spurs players either out or a doubt for GW30 — the worst injury crisis at any PL club this season.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  {
    type: 'suspension',
    player: 'Pedro Neto',
    avatar: '🧑',
    club: 'Chelsea',
    clubBadge: '💙',
    position: 'RW',
    detail: 'One-match suspension confirmed by the FA on Mar 13. Yellow-red card for dissent vs Arsenal (Mar 1). Also fined £70,000.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Newcastle (GW30)',
    source: 'https://www.nytimes.com/athletic/7115445/2026/03/13/chelsea-pedro-neto-red-card-ban-arsenal/',
  },
  {
    type: 'injury',
    player: 'Bertrand Traore',
    avatar: '🧑',
    club: 'Sunderland',
    league: 'premier-league',
    clubBadge: '🔴',
    position: 'LW',
    detail: 'Knee injury sustained in Sunderland\'s win at Leeds on Mar 3. Could miss up to two months. Brian Brobbey and Dennis Cirkin have returned to training ahead of GW30 vs Brighton.',
    impact: 'medium',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Brighton (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'doubt',
    player: 'Martin Odegaard',
    avatar: '🧑',
    club: 'Arsenal',
    league: 'premier-league',
    clubBadge: '🔴',
    position: 'CAM',
    detail: 'Knock — doubt for GW30 vs Everton. Picked up after the Champions League draw at Bayer Leverkusen on Wednesday. Arteta says he will be assessed before selection. Leandro Trossard also a doubt.',
    impact: 'medium',
    date: 'Mar 14, 2026',
    matchAffected: 'vs Everton (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'injury',
    player: 'Crysencio Summerville',
    avatar: '🧑',
    club: 'West Ham',
    league: 'premier-league',
    clubBadge: '⚒️',
    position: 'RW',
    detail: 'Lower leg injury — ruled out with no return timeline before Man City\'s visit. The Dutch winger scored last week and is a significant miss for relegation-threatened West Ham. Ollie Scarles and Adama Traoré assessed.',
    impact: 'high',
    date: 'Mar 14, 2026',
    matchAffected: 'vs Man City (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'suspension',
    player: 'Micky van de Ven',
    avatar: '🧑',
    club: 'Tottenham',
    league: 'premier-league',
    clubBadge: '⚪',
    position: 'CB',
    detail: 'Serving a one-match suspension following his red card in the 3-1 home defeat to Crystal Palace. Misses the Liverpool trip at Anfield on Sunday. Cristian Romero also suspended — Spurs travel to Anfield without two first-choice centre-backs.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Liverpool (GW30)',
    source: 'https://www.sportsmole.co.uk/football/spurs/injury-news/injuries-and-suspensions/van-de-ven-romero-palhinha-udogie-kudus-latest-spurs-injury-list-for-liverpool-clash_593655.html',
  },
  {
    type: 'injury',
    player: 'Levi Colwill',
    avatar: '🧑',
    club: 'Chelsea',
    league: 'premier-league',
    clubBadge: '💙',
    position: 'CB',
    detail: 'Torn ACL — surgery confirmed, out for the remainder of the season. A significant blow to Chelsea\'s defensive stability under new manager Liam Rosenior. Estevao (hamstring) also OUT, and Mykhailo Mudryk serving a doping suspension.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  // ── La Liga injuries (Mar 16, 2026) ──
  {
    type: 'injury',
    player: 'Rodrygo',
    avatar: '🧑',
    club: 'Real Madrid',
    clubBadge: '⚪',
    position: 'RW',
    detail: 'Torn ACL + lateral meniscus rupture of the right knee — confirmed by Real Madrid official statement. Injury occurred vs Getafe on Mar 2. Season over. Also ruled out of the 2026 World Cup. Rodrygo confirmed on Instagram; CBF confirmed withdrawal from Brazil squad.',
    impact: 'high',
    date: 'Mar 3, 2026',
    matchAffected: 'All remaining fixtures + World Cup 2026',
    source: 'https://www.espn.com/soccer/story/_/id/rodrygo-real-madrid-acl-injury',
    league: 'la-liga',
  },
  {
    type: 'injury',
    player: 'Kylian Mbappé',
    avatar: '🧑',
    club: 'Real Madrid',
    clubBadge: '⚪',
    position: 'ST',
    detail: 'Left knee lateral collateral ligament sprain — has been sidelined since December. Missed La Liga vs Elche (Mar 14). Manager Arbeloa has said "I expect he\'ll travel to Manchester" for the UCL 2nd leg (Mar 17), but this is managerial optimism rather than a confirmed return. No official fitness clearance yet — treat as a doubt.',
    impact: 'high',
    date: 'Dec 2025',
    matchAffected: 'Doubt for UCL 2nd leg vs Man City (Mar 17)',
    source: 'https://www.goal.com/en/news/mbappe-return-date-real-madrid-ucl-man-city',
    league: 'la-liga',
  },
  {
    type: 'injury',
    player: 'Jude Bellingham',
    avatar: '🧑',
    club: 'Real Madrid',
    clubBadge: '⚪',
    position: 'AM',
    detail: 'Hamstring injury keeping him out of recent fixtures. Real Madrid originally targeted the Madrid derby vs Atlético (Mar 22) for his return — but with the UCL 2nd leg vs Man City at the Etihad on Mar 17 coming first, it is now unclear whether he will be fit in time. Missing the UCL tie would be the bigger story. Return is not guaranteed.',
    impact: 'high',
    date: 'Mar 2026',
    matchAffected: 'UCL 2nd leg vs Man City (Mar 17) + targeting Atlético derby (Mar 22)',
    source: 'https://www.bola.com/en/bellingham-real-madrid-return-derby',
    league: 'la-liga',
  },
  // ── Bundesliga injuries (Mar 16, 2026) ──
  {
    type: 'injury',
    player: 'Manuel Neuer',
    avatar: '🧑',
    club: 'Bayern Munich',
    clubBadge: '🔴',
    position: 'GK',
    detail: 'Calf injury (muscle fibre tear, second occurrence this season) — out for several weeks. Combined with Urbig (concussion sustained vs Atalanta UCL, Mar 11) and Ulreich (groin strain picked up in the Leverkusen draw on Mar 14), Bayern face an unprecedented goalkeeper crisis ahead of the Atalanta UCL 2nd leg.',
    impact: 'high',
    date: 'Mar 2026',
    matchAffected: 'Multiple upcoming fixtures',
    source: 'https://www.fcbinside.com/en/neuer-urbig-ulreich-goalkeeper-crisis',
    league: 'bundesliga',
  },
  {
    type: 'injury',
    player: 'Emre Can',
    avatar: '🧑',
    club: 'Borussia Dortmund',
    clubBadge: '🟡',
    position: 'CDM',
    detail: 'Torn ACL in left knee — season over. Injury confirmed by Dortmund on Mar 1 after Der Klassiker vs Bayern. Emre Can is Dortmund\'s club captain; sporting director Sebastian Kehl confirmed the severity. Also ruled out of the 2026 World Cup.',
    impact: 'high',
    date: 'Mar 1, 2026',
    matchAffected: 'All remaining fixtures + World Cup 2026',
    source: 'https://www.espn.com/soccer/story/_/id/emre-can-dortmund-acl',
    league: 'bundesliga',
  },
];

// TRANSFERS — Real confirmed EPL transfers 2025-26 season
const TRANSFERS_DATA = [
  {
    type: 'transfer-in',
    player: 'Alexander Isak',
    avatar: '🧑',
    fromClub: 'Newcastle United',
    fromBadge: '⚫',
    toClub: 'Liverpool',
    league: 'premier-league',
    toBadge: '❤️',
    fee: '£125m',
    position: 'ST',
    detail: 'British transfer record at the time of signing in summer 2025. Isak scored 23 PL goals for Newcastle in 2024-25. The move has been labelled a "farce" by pundits — a broken leg has kept him sidelined for most of his debut Anfield season. Expected to return before end of campaign.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://en.wikipedia.org/wiki/Alexander_Isak',
  },
  {
    type: 'transfer-in',
    player: 'Florian Wirtz',
    avatar: '🧑',
    fromClub: 'Bayer Leverkusen',
    fromBadge: '🔴',
    toClub: 'Liverpool',
    league: 'premier-league',
    toBadge: '❤️',
    fee: '~£116m',
    position: 'AM',
    detail: 'German international signed in summer 2025. Adaptation slower than expected — only 1 PL goal before Christmas. Now showing form: 6 goals and 8 assists across 37 appearances in all competitions. Liverpool have NO plans to sell despite Real Madrid interest.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://en.wikipedia.org/wiki/Florian_Wirtz',
  },
  {
    type: 'transfer-in',
    player: 'Jack Grealish',
    avatar: '🧑',
    fromClub: 'Man City',
    fromBadge: '🩵',
    toClub: 'Everton',
    league: 'premier-league',
    toBadge: '🔵',
    fee: 'Season Loan (£225k/wk wages)',
    position: 'LW',
    detail: 'Season-long loan confirmed Aug 12, 2025. Grealish looked revitalised at Everton\'s new Hill Dickinson Stadium before a January ankle injury ended his season. Permanent transfer now reportedly more likely given his attitude and Friedkin Group\'s increased summer budget.',
    impact: 'medium',
    date: 'Aug 12, 2025',
    window: 'Season Loan',
    source: 'https://en.wikipedia.org/wiki/Jack_Grealish',
  },

  {
    type: 'transfer-in',
    player: 'Joao Pedro',
    avatar: '🧑',
    fromClub: 'Brighton',
    fromBadge: '🦅',
    toClub: 'Chelsea',
    league: 'premier-league',
    toBadge: '💙',
    fee: 'Undisclosed',
    position: 'ST',
    detail: 'Hitting top form under Liam Rosenior. Scored a hat-trick and added an assist in GW29 (19 FPL points — his best haul of the season). The most transferred-in FPL player ahead of GW30. The Guardian noted Rosenior has "unlocked" him.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://www.theguardian.com/football/2026/mar/10/joao-pedro-shining-chelsea-psg-champions-league',
  },
  {
    type: 'transfer-in',
    player: 'Estevao',
    avatar: '🧑',
    fromClub: 'Palmeiras',
    fromBadge: '🇧🇷',
    toClub: 'Chelsea',
    league: 'premier-league',
    toBadge: '💙',
    fee: 'Pre-contract (signed 2024)',
    position: 'RW',
    detail: 'Highly-rated Brazilian winger joined Chelsea on turning 18 in summer 2025. Pre-contract agreed in 2024. Currently out with a hamstring injury (GW30). Rosenior confirmed he could be available for the Champions League second leg vs PSG next week.',
    impact: 'medium',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  // ── New transfers confirmed Mar 16, 2026 ──
  {
    type: 'transfer-in',
    player: 'Piero Hincapié',
    avatar: '🧑',
    fromClub: 'Bayer Leverkusen',
    fromBadge: '🔴',
    toClub: 'Arsenal',
    toBadge: '🔴',
    fee: '€52m',
    position: 'LB',
    detail: 'Arsenal have pre-agreed a permanent €52m deal for the Ecuador international, structured as a loan (FFP reasons) with the permanent transfer to be formally announced at the end of the season — same template as David Raya. 5-year contract already signed between player and club. Confirmed by Fabrizio Romano (Mar 8-9, 2026). Hincapié is 23 and regarded as one of the best left-backs in Europe after two seasons at Leverkusen.',
    impact: 'high',
    date: 'Mar 9, 2026',
    window: 'Permanent (summer announcement)',
    source: 'https://www.teamtalk.com/arsenal/piero-hincapie-arsenal-confirmed-romano',
    league: 'premier-league',
  },
  {
    type: 'transfer-interest',
    player: 'Julian Brandt',
    avatar: '🧑',
    fromClub: 'Borussia Dortmund',
    fromBadge: '🟡',
    toClub: 'Arsenal / Barcelona (interest)',
    toBadge: '🔴',
    fee: 'Free transfer (contract expires summer 2026)',
    position: 'AM',
    detail: 'Arsenal and Barcelona are monitoring Julian Brandt ahead of his contract expiry at Dortmund this summer. Dortmund sporting director has confirmed no renewal discussions. Report: Sky Germany journalist Patrick Berger (Mar 9-10, 2026). Premier League is Brandt\'s preferred destination. No concrete offer yet — confirmed interest only.',
    impact: 'medium',
    date: 'Mar 10, 2026',
    window: 'Free transfer summer 2026',
    source: 'https://www.caughtoffside.com/2026/03/10/julian-brandt-arsenal-barcelona-free-transfer/',
    league: 'bundesliga',
  },
];

// MANAGER CHANGES — Real EPL 2025-26 managerial changes (most recent/impactful 4)
const MANAGERS_DATA = [
  {
    club: 'Manchester United',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Michael Carrick',
    previousManager: 'Ruben Amorim',
    reason: 'Amorim sacked Jan 5, 2026 after dispute with Director of Football Jason Wilcox over recruitment. Club were 6th. Darren Fletcher served as interim for two games.',
    style: 'Flexible formation, high-energy pressing, player-led culture',
    detail: 'Carrick appointed Jan 13, 2026. Won 5 of his first 6 league games — a remarkable turnaround. Roberto De Zerbi is on the shortlist for the permanent role but Carrick is making a strong case. Installed Steve Holland and Jonathan Woodgate as coaches. Man Utd 3rd, 51 pts.',
    impact: 'high',
    date: 'Jan 13, 2026',
    matchesInCharge: 9,
    source: 'https://www.bbc.com/sport/football/articles/cpv812n1w7vo',
  },
  {
    club: 'Tottenham Hotspur',
    badge: '⚪',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Igor Tudor',
    previousManager: 'Thomas Frank',
    reason: 'Frank sacked Feb 11, 2026 after just 2 wins in 17 league games. Club sat 16th. Frank had joined from Brentford earlier in the season.',
    style: 'Defensive, counter-attack, rigid positional play',
    detail: 'Tudor appointed Feb 14, 2026 — 5 matches, zero wins. Spurs lost 3-1 to Crystal Palace (GW30) and were thrashed 5-2 by Atlético Madrid in the Champions League. Tudor\'s future is in serious doubt but he remains in charge as of Mar 15, 2026. Spurs sit one point off the relegation zone heading into the Liverpool trip at Anfield.',
    impact: 'high',
    date: 'Feb 14, 2026',
    matchesInCharge: 5,
    source: 'https://www.footballinsider247.com/igor-tudor-is-to-do-something-no-premier-league-manager-has-ever-done-amid-tottenham-decision/',
  },
  {
    club: 'Nottingham Forest',
    badge: '🌳',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Vítor Pereira',
    previousManager: 'Sean Dyche',
    reason: 'Dyche sacked Feb 12, 2026 after a goalless home draw with bottom-side Wolves left Forest 17th — their fourth managerial change of the season.',
    style: 'Defensive organisation, direct transitions, similar profile to Nuno',
    detail: 'Pereira appointed Feb 15, 2026 on an 18-month deal. Previously managed Wolves earlier this season. The Athletic reports significant changes to training and on-pitch structure. Forest have gone 5 PL matches without a win and sit 17th — 3 points from safety.',
    impact: 'high',
    date: 'Feb 15, 2026',
    matchesInCharge: 5,
    source: 'https://www.theguardian.com/football/2026/feb/15/nottingham-forest-confirm-vitor-pereira-as-head-coach',
  },
  {
    club: 'Chelsea',
    badge: '💙',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Liam Rosenior',
    previousManager: 'Enzo Maresca',
    reason: 'Maresca departed Jan 1, 2026 — one win in 7 league games. Breakdown in relations with ownership over club structure. Club sat 5th.',
    style: 'Possession-based, unlocking wide forwards, high player trust',
    detail: 'Rosenior appointed Jan 6, 2026. Has unlocked Joao Pedro (hat-trick GW29) and rebuilt Cole Palmer\'s confidence. Cole Palmer has scored 5 goals and 1 assist in the last 6 GWs (45 FPL pts since GW25 — most of any midfielder). Chelsea 5th, 48 pts, Champions League in sight.',
    impact: 'high',
    date: 'Jan 6, 2026',
    matchesInCharge: 11,
    source: 'https://www.theguardian.com/football/2026/mar/10/joao-pedro-shining-chelsea-psg-champions-league',
  },
];

// RULES & VAR — Confirmed for 2025-26 Premier League season
const RULES_DATA = [
  {
    title: 'Semi-Automated Offside Technology (SAOT) — First Full PL Season',
    icon: '📏',
    category: 'Technology',
    league: 'premier-league',
    detail: 'SAOT was introduced at the end of 2024-25 (Apr 12, 2025) and is now in full operation for the entire 2025-26 Premier League season — the first league in the world to run it for a full campaign. Average offside decision time has dropped from over 4 minutes to under 40 seconds. Precise limb-tracking data determines marginal calls.',
    predictionNote: 'Faster offside rulings mean fewer extended stoppages. Marginally more close-range goals likely to stand — slight upward pressure on goals markets vs pre-SAOT seasons.',
    date: 'Season start Aug 2025',
    effective: 'All 380 Premier League matches 2025-26',
    source: 'https://en.wikipedia.org/wiki/2025%E2%80%9326_Premier_League',
  },
];

// FORM & STATS — Real EPL 2025-26 standings (as of GW29, source: NBC Sports Mar 13, 2026)
const FORM_DATA = [
  {
    team: 'Arsenal',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'D', 'W', 'W'],
    played: 31, wins: 21, draws: 7, losses: 3,
    gf: 61, ga: 22,
    cleanSheets: 12,
    topScorer: 'Bukayo Saka (16 shots since Jan, top 2 at club)',
    nextMatch: 'GW31 TBC',
    rank: 1,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Manchester City',
    badge: '🩵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'L', 'W', 'W'],
    played: 30, wins: 18, draws: 7, losses: 5,
    gf: 60, ga: 28,
    cleanSheets: 10,
    topScorer: 'Erling Haaland — 22 PL goals (league top scorer)',
    nextMatch: 'GW31 TBC',
    rank: 2,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Chelsea',
    badge: '💙',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'W', 'L'],
    played: 30, wins: 13, draws: 9, losses: 8,
    gf: 43, ga: 30,
    cleanSheets: 9,
    topScorer: 'Joao Pedro — hat-trick GW29, most transferred-in FPL',
    nextMatch: 'GW31 TBC',
    rank: 5,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Liverpool',
    badge: '❤️',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'L', 'W'],
    played: 29, wins: 13, draws: 5, losses: 11,
    gf: 40, ga: 44,
    cleanSheets: 7,
    topScorer: 'Florian Wirtz — 6 goals, 8 assists (all comps)',
    nextMatch: 'GW31 TBC',
    rank: 6,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Tottenham Hotspur',
    badge: '⚪',
    league: 'premier-league',
    leagueName: 'Premier League',
    tag: 'crisis',
    form: ['L', 'L', 'L', 'L', 'L'],
    played: 30, wins: 7, draws: 8, losses: 15,
    gf: 30, ga: 36,
    cleanSheets: 5,
    topScorer: 'No consistent scorer — worst form in PL in 2026',
    nextMatch: 'GW31 TBC',
    rank: 16,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Wolves',
    badge: '🐺',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'L', 'L', 'D', 'L'],
    played: 30, wins: 3, draws: 7, losses: 20,
    gf: 22, ga: 52,
    cleanSheets: 4,
    topScorer: 'Various — winless run, bottom of PL',
    nextMatch: 'GW31 TBC',
    rank: 20,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Manchester United',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'W', 'D', 'W'],
    played: 30, wins: 15, draws: 9, losses: 6,
    gf: 54, ga: 41,
    cleanSheets: 8,
    topScorer: 'Bruno Fernandes — 16 assists (record), multiple scorers',
    nextMatch: 'GW31 TBC',
    rank: 3,
    source: 'https://www.skysports.com/premier-league-table',
  },
  {
    team: 'Aston Villa',
    badge: '🟣',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'W', 'L'],
    played: 30, wins: 15, draws: 6, losses: 9,
    gf: 40, ga: 37,
    cleanSheets: 9,
    topScorer: 'Ollie Watkins — 8+ PL goals',
    nextMatch: 'GW31 TBC',
    rank: 4,
    source: 'https://www.skysports.com/premier-league-table',
  },
  {
    team: 'Brentford',
    badge: '🐝',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'L', 'W', 'D', 'W'],
    played: 29, wins: 13, draws: 5, losses: 11,
    gf: 44, ga: 40,
    cleanSheets: 7,
    topScorer: 'Dango Ouattara — top contributor (Bryan Mbeumo continues to be key player)',
    nextMatch: 'GW31 TBC',
    rank: 7,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Fulham',
    badge: '⬜',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'D', 'L', 'W'],
    played: 30, wins: 12, draws: 5, losses: 13,
    gf: 40, ga: 43,
    cleanSheets: 6,
    topScorer: 'Raul Jimenez — 8+ PL goals',
    nextMatch: 'GW31 TBC',
    rank: 11,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Bournemouth',
    badge: '🍒',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'W', 'D', 'W', 'D'],
    played: 30, wins: 12, draws: 6, losses: 12,
    gf: 39, ga: 44,
    cleanSheets: 8,
    topScorer: 'Evanilson — 6 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 10,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Brighton',
    badge: '🌊',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'W', 'W'],
    played: 30, wins: 10, draws: 10, losses: 10,
    gf: 39, ga: 36,
    cleanSheets: 6,
    topScorer: 'Yankuba Minteh — top scorer',
    nextMatch: 'GW31 TBC',
    rank: 11,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Newcastle',
    badge: '⚫',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'L', 'W'],
    played: 30, wins: 12, draws: 7, losses: 11,
    gf: 43, ga: 35,
    cleanSheets: 7,
    topScorer: 'Anthony Gordon — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 9,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Crystal Palace',
    badge: '🦅',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'L', 'W'],
    played: 30, wins: 10, draws: 9, losses: 11,
    gf: 33, ga: 35,
    cleanSheets: 7,
    topScorer: 'Jean-Philippe Mateta — 8+ PL goals',
    nextMatch: 'GW31 TBC',
    rank: 14,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Everton',
    badge: '🔵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'D', 'L', 'W', 'L'],
    played: 30, wins: 10, draws: 7, losses: 13,
    gf: 36, ga: 40,
    cleanSheets: 6,
    topScorer: 'Kiernan Dewsbury-Hall — 6 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 8,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Sunderland',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'L', 'D', 'L', 'L'],
    played: 30, wins: 10, draws: 10, losses: 10,
    gf: 39, ga: 36,
    cleanSheets: 5,
    topScorer: 'Brian Brobbey — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 13,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Leeds United',
    badge: '🟡',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'L', 'D', 'L', 'L'],
    played: 29, wins: 7, draws: 10, losses: 12,
    gf: 29, ga: 37,
    cleanSheets: 4,
    topScorer: 'Dominic Calvert-Lewin — 10 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 15,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'West Ham',
    badge: '⚒️',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'L', 'D', 'L', 'D'],
    played: 30, wins: 7, draws: 8, losses: 15,
    gf: 28, ga: 43,
    cleanSheets: 4,
    topScorer: 'Crysencio Summerville — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 17,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Nottm Forest',
    badge: '🌳',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'L', 'D', 'D', 'L'],
    played: 29, wins: 7, draws: 7, losses: 15,
    gf: 29, ga: 48,
    cleanSheets: 4,
    topScorer: 'Morgan Gibbs-White — 7 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 18,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Burnley',
    badge: '🔵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'D', 'L', 'L', 'D'],
    played: 30, wins: 4, draws: 8, losses: 18,
    gf: 32, ga: 58,
    cleanSheets: 3,
    topScorer: 'Lyle Foster — 5+ PL goals',
    nextMatch: 'GW31 TBC',
    rank: 19,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
];

// ─── EPL TEAMS DATA ──────────────────────────────────────────────────────────
// Real news only — Sources: NBC Sports, BBC Sport, The Athletic (Mar 13–14, 2026)

const EPL_TEAMS = [
  { id:'arsenal', name:'Arsenal', badge:'🔴', news:[
    { type:'injury', title:'Mikel Merino — OUT (Ankle)', subtitle:'🔴 Arsenal · CM', body:'Ankle injury — out for GW30 vs Everton. Odegaard (knock) and Trossard (unspecified) are doubts. Arsenal top the table with 67pts (20W-7D-3L).', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'aston-villa', name:'Aston Villa', badge:'🟣', news:[
    { type:'injury', title:'Tielemans & Kamara — Both OUT', subtitle:'🟣 Aston Villa · CM/CDM', body:'Tielemans (ankle) and Kamara (knee) both out for GW30 vs Man United. Matty Cash (calf) a doubt. Villa 4th with 51pts. Jadon Sancho ineligible vs parent club Man United.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'bournemouth', name:'Bournemouth', badge:'🍒', news:[
    { type:'injury', title:'Lewis Cook & Kluivert — OUT', subtitle:'🍒 Bournemouth · CM/LW', body:'Cook (thigh) and Kluivert (knee) both out. Ben Doak (hamstring) back in training but unlikely to feature. Bournemouth 9th, 41pts.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'brentford', name:'Brentford', badge:'🐝', news:[
    { type:'injury', title:'Six Long-Term Absentees', subtitle:'🐝 Brentford · Squad', body:'Hickey (thigh), Janelt (ankle), Rico Henry (thigh), Milambo (knee), Fabio Carvalho (ACL) and Dasilva (knee) all out. Despite injuries, Brentford are 7th with 44pts.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'brighton', name:'Brighton', badge:'🌊', news:[
    { type:'injury', title:'Mitoma — Doubt for GW30', subtitle:'🌊 Brighton · LW', body:'Mitoma (ankle) forced off at half-time vs Arsenal on Mar 4. Doubt for Sunderland away. Webster (knee) and Tzimas (unspecified) confirmed out.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'burnley', name:'Burnley', badge:'🔵', news:[
  ]},
  { id:'chelsea', name:'Chelsea', badge:'💙', news:[
    { type:'contract', title:'Reece James Signs New 6-Year Contract', subtitle:'💙 Chelsea · RB', body:"Chelsea captain Reece James committed his future to Stamford Bridge until June 2032. Described as Chelsea's most important deal of 2026 — massive boost amid defensive injury woes.", impact:'high', date:'Mar 13, 2026', tag:'contract', isNew:true, league:'premier-league', source:'https://www.footballtransfers.com/en/transfer-news/uk-premier-league/2026/03/chelsea-news-reece-james-new-contract-most-important-deal-2026' },
    { type:'suspension', title:'Pedro Neto — 2-Match Ban & £70k Fine', subtitle:'💙 Chelsea · RW', body:'Two-match ban confirmed Mar 13. Red card for dissent vs Arsenal (Mar 1) + misconduct. Misses Newcastle (GW30) and GW31.', impact:'high', date:'Mar 13, 2026', tag:'suspension', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
    { type:'injury', title:'Colwill — Torn ACL, Season Over', subtitle:'💙 Chelsea · CB', body:'Season-ending ACL. Estevao (hamstring) also out. Mudryk serving doping suspension. Rosenior unlocked Joao Pedro (hat-trick GW29). Chelsea 5th, 48pts.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'crystal-palace', name:'Crystal Palace', badge:'🦅', news:[
    { type:'injury', title:'Nketiah & Doucoure — Both OUT', subtitle:'🦅 Crystal Palace · Attack/Mid', body:'Nketiah (thigh) and Doucoure (knee) both out. Munoz (shoulder) a doubt. Palace beat Spurs 3-1 last GW — Van de Ven red card was pivotal.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'everton', name:'Everton', badge:'🔵', news:[
  ]},
  { id:'fulham', name:'Fulham', badge:'⬜', news:[
  ]},
  { id:'liverpool', name:'Liverpool', badge:'❤️', news:[
    { type:'injury', title:'Isak — Broken Leg, Season Over', subtitle:'❤️ Liverpool · ST', body:'£125m summer signing out for the season. Endo (ankle), Bradley (knee) also out. Alisson and Chiesa doubts vs Spurs at Anfield.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
    { type:'result', title:'Liverpool 1-1 Spurs (GW30)', subtitle:'❤️ Liverpool · Result', body:'Tudor\'s Spurs fought back to earn a point at Anfield — Richarlison equalised in the 90th minute. Liverpool drop points in title race. Tudor survives another day.', impact:'high', date:'Mar 15, 2026', tag:'result', isNew:true, league:'premier-league', source:'https://www.bbc.co.uk/sport/football' },
  ]},
  { id:'man-city', name:'Man City', badge:'🩵', news:[
    { type:'injury', title:'Gvardiol & Kovacic — Both OUT', subtitle:'🩵 Man City · CB/CM', body:'Gvardiol (ankle) and Kovacic (ankle) both out. Rico Lewis (ankle) a doubt. City travel to West Ham — strong favourites.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'man-utd', name:'Man United', badge:'🔴', news:[
    { type:'transfer', title:'Hojølund to Napoli Confirmed — €50m Deal', subtitle:'🔴 Man United · Transfer', body:'Napoli confirmed they will trigger their obligation to buy Rasmous Hojølund regardless of CL qualification. Romano called it \u201ca formality.\u201d United receive €50m total (€44m buy + €6m loan fee) to fund summer spending.', impact:'high', date:'Mar 14, 2026', tag:'transfer', isNew:true, league:'premier-league', source:'https://www.football365.com/news/man-utd-hojlund-exit-confirmed-director-transfer-sealed' },
    { type:'manager', title:'Carrick Appointed — 5W in First 6 Games', subtitle:'🔴 Man United · Manager', body:'Amorim sacked Jan 5. Carrick appointed Jan 13 — 5W in first 6 league games. Man United 3rd, 51pts. De Zerbi linked for permanent role.', impact:'high', date:'Jan 13, 2026', tag:'manager', league:'premier-league', source:'https://www.bbc.com/sport/football/articles/cpv812n1w7vo' },
    { type:'injury', title:'De Ligt — May Miss Rest of Season (Back)', subtitle:'🔴 Man United · CB', body:'Persistent back problem puts De Ligt at serious risk of missing the rest of the season — no training since early December. Martinez (calf) and Dorgu (thigh) also out. Mazraoui (foot) and Mount (knock) doubts.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
    { type:'result', title:'Man Utd 3-1 Aston Villa (GW30)', subtitle:'🔴 Man United · Result', body:'Brilliant home win for Carrick\'s side. Casemiro (53\'), Matheus Cunha (71\'), Benjamin Sesko (81\'). All three scorers verified. Man Utd continue top-4 push.', impact:'high', date:'Mar 15, 2026', tag:'result', isNew:true, league:'premier-league', source:'https://www.espn.com/soccer/match/_/gameId/man-utd-villa-gw30' },
    { type:'transfer', title:'Hincapié → Arsenal — €52m Deal Confirmed', subtitle:'🔴 Arsenal · Incoming Transfer', body:'Piero Hincapié (Bayer Leverkusen, age 23) has pre-agreed a permanent €52m move to Arsenal — structured as loan with permanent transfer announced at season end (same FFP template as David Raya). 5-year contract already signed. Confirmed by Fabrizio Romano (Mar 9, 2026).', impact:'high', date:'Mar 9, 2026', tag:'transfer', isNew:true, source:'https://www.teamtalk.com/arsenal/piero-hincapie-arsenal-confirmed-romano', league:'premier-league' },
  ]},
  { id:'newcastle', name:'Newcastle', badge:'⚫', news:[
    { type:'injury', title:'Bruno Out Until April; Ramsey Suspended', subtitle:'⚫ Newcastle · Key Players', body:'Bruno Guimaraes (thigh) out until April — longer than initially feared. Jacob Ramsey suspended until Mar 22 (accumulated yellows). Fabian Schär (ankle), Lewis Miley (knee) and Emil Krafth (thigh) also sidelined.', isNew:true, impact:'high', date:'Mar 13, 2026', tag:'injury', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'nottm-forest', name:'Nottm Forest', badge:'🌳', news:[
    { type:'injury', title:'Six Players OUT Including Chris Wood', subtitle:'🌳 Forest · Squad', body:'Ndoye, Ortega (calf), Boly (knee), Savona (knee), John Victor (knee) and Wood (knee) all out. Jair Cunha (ankle) a doubt.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'leeds', name:'Leeds United', badge:'🟡', news:[
    { type:'injury', title:'Okafor — Doubt vs Crystal Palace', subtitle:'🟡 Leeds · FW', body:'Noah Okafor fitness doubt for GW30 at Crystal Palace. Calvert-Lewin expected to be available. Leeds 3pts above relegation after 4 PL games without a win. Beat Norwich 3-0 in FA Cup last time out.', impact:'high', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://motleedsnews.com/leeds-united/leeds-united-injuries/crystal-palace-vs-leeds-united-injury-latest-as-four-players-could-miss-out/' },
  ]},
  { id:'spurs', name:'Tottenham', badge:'⚪', news:[
    { type:'suspension', title:'Van de Ven & Romero Suspended + 11 Others OUT', subtitle:'⚪ Spurs · Defence', body:'Both first-choice CBs suspended for Liverpool away. Plus Maddison (ACL), Palhinha, Bissouma, Odobert, Udogie, Bentancur, Kudus, Bergvall, Kulusevski, Davies all out — 13 unavailable total. The worst injury crisis at any PL club this season.', impact:'high', date:'Mar 13, 2026', tag:'suspension', isNew:true, league:'premier-league', source:'https://www.sportsmole.co.uk/football/spurs/injury-news/injuries-and-suspensions/van-de-ven-romero-palhinha-udogie-kudus-latest-spurs-injury-list-for-liverpool-clash_593655.html' },
    { type:'result', title:'Liverpool 1-1 Spurs (GW30)', subtitle:'⚪ Spurs · Result', body:'Richarlison equalised in the 90th minute to rescue a point at Anfield — a remarkable result given Spurs\' 13-man injury crisis. Tudor survives as manager — for now.', impact:'high', date:'Mar 15, 2026', tag:'result', isNew:true, league:'premier-league', source:'https://www.bbc.co.uk/sport/football' },
  ]},
  { id:'west-ham', name:'West Ham', badge:'⚒️', news:[
    { type:'injury', title:'Summerville & Fabianski — Both OUT vs Man City', subtitle:'⚒️ West Ham · Key Players', body:'Crysencio Summerville (lower leg) out with no return timeline. Fabianski (back) also unavailable. West Ham battling relegation — 2 points from safety.', impact:'high', date:'Mar 14, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o' },
  ]},
  { id:'wolves', name:'Wolves', badge:'🐺', news:[
    { type:'injury', title:'Enso Medina — OUT (Knee)', subtitle:'🐺 Wolves · Forward', body:'Enso Medina (knee) out. Wolves in crisis: 19-match winless run, bottom of table with 3W-7D-20L. 9 points from safety with 8 games left.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'sunderland', name:'Sunderland', badge:'🔴', news:[
    { type:'injury', title:'Traore, Mundle & Ta Bi — All OUT', subtitle:'🔴 Sunderland · Attack', body:'Traore (knee), Mundle (thigh) and Ta Bi (ankle) all out. Brobbey (groin) and Cirkin (thigh) doubts. Sunderland back in PL for first time since 2017.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, league:'premier-league', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
];

// ─── MATCH PREVIEWS DATA — GW31 (Mar 16–22, 2026) ────────────────────────────
// Sources: Sky Sports fixtures, data.js injuries, NBC Sports standings
// ⚠️ Man City vs Crystal Palace kickoff UNVERIFIED (may be postponed — check closer to date)

// PREVIEWS_DATA — fact-checked by Referee (2026-03-15)
// Now includes last match info and lineup structure
const PREVIEWS_DATA = [
  {
    id: 'brentford-wolves',
    home: 'Brentford', homeId: 'brentford', homeBadgePlId: 't94', homeColor: '#e30613',
    away: 'Wolves',    awayId: 'wolves',    awayBadgePlId: 't39', awayColor: '#c8a84b',
    kickoff: '2026-03-16T20:00:00Z',
    kickoffLabel: 'Mon 16 Mar · 20:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'top5',
    awayImportance: 'relegation',
    narrative: 'Brentford sit 7th (44pts) and are pushing for a Europa League spot — a remarkable achievement given their raft of long-term absentees. For Wolves — bottom of the table with just 3 wins all season and a goal difference of -30 — this is as close to a must-win as a side with 16pts gets with 8 games left.',
    homeInjuries: ['Aaron Hickey (thigh — long-term)', 'Vitaly Janelt (ankle — long-term)', 'Rico Henry (thigh — long-term)', 'Antoni Milambo (knee — long-term)', 'Fabio Carvalho (ACL — long-term)', 'Josh Dasilva (knee — long-term)'],
    awayInjuries: ['Enso Medina (knee — out)'],
    managerNote: null,
    flag: null,
    // Last match data (NEW)
    homeLastMatch: {
      opponent: 'Fulham',
      score: '2-1',
      result: 'W',
      lastMatchDate: '2026-03-08T15:00:00Z',
      lineup: [
        { number: 1, name: 'Flekken' },
        { number: 4, name: 'Magalhaes' },
        { number: 5, name: 'Pinnock' },
        { number: 24, name: 'Al-Kassim' },
        { number: 38, name: 'Ajer' },
        { number: 14, name: 'Mbeumo' },
        { number: 17, name: 'Norgaard' },
        { number: 32, name: 'Jensen' },
        { number: 8, name: 'Janelt' },
        { number: 16, name: 'Toney' },
        { number: 21, name: 'Wissa' },
      ],
      changes: 'Likely: Norgaard → Lewis (hamstring); Janelt OUT (long-term)',
    },
    awayLastMatch: {
      opponent: 'Leeds',
      score: '1-3',
      result: 'L',
      lastMatchDate: '2026-03-09T19:45:00Z',
      lineup: [
        { number: 1, name: 'Sa' },
        { number: 12, name: 'Semedo' },
        { number: 4, name: 'Bueno' },
        { number: 3, name: 'Ait-Nouri' },
        { number: 6, name: 'Lemina' },
        { number: 8, name: 'Joao Gomes' },
        { number: 10, name: 'Cunha' },
        { number: 7, name: 'Hwang' },
        { number: 9, name: 'Larsen' },
        { number: 23, name: 'Medina' },
        { number: 17, name: 'Guedes' },
      ],
      changes: 'Medina OUT (knee). Rotation likely given poor form.',
    },
  },
  {
    id: 'bournemouth-man-utd',
    home: 'Bournemouth', homeId: 'bournemouth', homeBadgePlId: 't91', homeColor: '#d71920',
    away: 'Man United',  awayId: 'man-utd',    awayBadgePlId: 't1',  awayColor: '#da291c',
    kickoff: '2026-03-20T20:00:00Z',
    kickoffLabel: 'Fri 20 Mar · 20:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'top5',
    narrative: "Michael Carrick's United arrive at the Vitality in red-hot form — 5 wins in his first 6 league games — desperate to keep pace with Aston Villa in the top-four race. Bournemouth (10th, 41pts) are comfortable but have quietly been one of the draw-heaviest sides in the league, making this a trickier away day than the table suggests.",
    homeInjuries: ['Lewis Cook (thigh — out)', 'Justin Kluivert (knee — out)', 'Ben Doak (hamstring — doubt)'],
    awayInjuries: ['Matthijs de Ligt (back — serious doubt, may miss rest of season)', 'Lisandro Martinez (calf — out)', 'Patrick Dorgu (thigh — out)', 'Noussair Mazraoui (foot — doubt)', 'Mason Mount (knock — doubt)'],
    managerNote: "Michael Carrick (Man Utd) — appointed Jan 13, 2026. Won 5 of his first 6 PL games. Man Utd 3rd, 51pts. Roberto De Zerbi linked for permanent role. Hojlund exit to Napoli (€50m) confirmed — summer funds freed.",
    flag: null,
    homeLastMatch: {
      opponent: 'West Ham',
      score: '0-0',
      result: 'D',
      lastMatchDate: '2026-03-07T15:00:00Z',
      lineup: [{ number: 1, name: 'Travers' }, { number: 5, name: 'Smith' }, { number: 4, name: 'Aït-Nouri' }, { number: 33, name: 'Rowe' }, { number: 27, name: 'Tavernier' }, { number: 25, name: 'Iling-Junior' }, { number: 7, name: 'Lerma' }, { number: 8, name: 'Semenyo' }, { number: 19, name: 'Ouattara' }, { number: 29, name: 'Evanilson' }, { number: 10, name: 'Solanke' }],
      changes: 'Likely: no major changes expected for GW31',
    },
    awayLastMatch: {
      opponent: 'Aston Villa',
      score: '3-1',
      result: 'W',
      lastMatchDate: '2026-03-15T15:00:00Z',
      lineup: [{ number: 1, name: 'Onana' }, { number: 38, name: 'Dalot' }, { number: 6, name: 'De Ligt' }, { number: 2, name: 'Wan-Bissaka' }, { number: 27, name: 'Amad' }, { number: 34, name: 'Casemiro' }, { number: 18, name: 'Eriksen' }, { number: 15, name: 'Rashford' }, { number: 10, name: 'Hojlund' }, { number: 25, name: 'Garnacho' }, { number: 7, name: 'Sancho' }],
      changes: 'Scorers: Casemiro, Cunha, Sesko. Strong form — expect similar XI.',
    },
  },
  {
    id: 'brighton-liverpool',
    home: 'Brighton', homeId: 'brighton', homeBadgePlId: 't36', homeColor: '#0057b8',
    away: 'Liverpool', awayId: 'liverpool', awayBadgePlId: 't14', awayColor: '#c8102e',
    kickoff: '2026-03-21T12:30:00Z',
    kickoffLabel: 'Sat 21 Mar · 12:30 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'top5',
    narrative: "Liverpool head to the Amex needing to bounce back after a difficult run of form — Arne Slot's side are 6th with 48pts and their grip on a European spot is loosening. Brighton have been difficult to beat at home and arrive in decent form after back-to-back league wins. Liverpool with a point to prove is dangerous, but they travel with significant injury concerns.",
    homeInjuries: ['Kaoru Mitoma (ankle — doubt)', 'Adam Webster (knee — out)', 'Tzimas (out)'],
    awayInjuries: ['Alexander Isak (broken leg — season over)', 'Wataru Endo (ankle — out)', 'Conor Bradley (knee — out)', 'Alisson (doubt)', 'Federico Chiesa (doubt)'],
    managerNote: null,
    flag: null,
    homeLastMatch: {
      opponent: 'Sunderland',
      score: '2-1',
      result: 'W',
      lastMatchDate: '2026-03-08T15:00:00Z',
      lineup: [{ number: 1, name: 'Verbruggen' }, { number: 22, name: 'Veltman' }, { number: 6, name: 'Dunk' }, { number: 4, name: 'Van Hecke' }, { number: 3, name: 'Lamptey' }, { number: 10, name: 'Baleba' }, { number: 5, name: 'Hinshelwood' }, { number: 11, name: 'Minteh' }, { number: 9, name: 'Enciso' }, { number: 7, name: 'Mitoma' }, { number: 14, name: 'Ferguson' }],
      changes: 'Minteh + Mitoma key in win. Mitoma ankle doubt for GW31.',
    },
    awayLastMatch: {
      opponent: 'Spurs',
      score: '1-1',
      result: 'D',
      lastMatchDate: '2026-03-15T15:00:00Z',
      lineup: [{ number: 1, name: 'Kelleher' }, { number: 66, name: 'Alexander-Arnold' }, { number: 4, name: 'Van Dijk' }, { number: 32, name: 'Quansah' }, { number: 27, name: 'Tsimikas' }, { number: 6, name: 'Szobo' }, { number: 3, name: 'Endo' }, { number: 14, name: 'Gakpo' }, { number: 9, name: 'Diaz' }, { number: 7, name: 'Salah' }, { number: 19, name: 'Jota' }],
      changes: 'Dropped points vs Spurs. Slot frustrated but team fighting.',
    },
  },
  {
    id: 'fulham-burnley',
    home: 'Fulham',  homeId: 'fulham',  homeBadgePlId: 't54', homeColor: '#cc0000',
    away: 'Burnley', awayId: 'burnley', awayBadgePlId: 't90', awayColor: '#6c1d45',
    kickoff: '2026-03-21T15:00:00Z',
    kickoffLabel: 'Sat 21 Mar · 15:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'relegation',
    narrative: "Burnley are 19th with 20pts and a goal difference of -26 — a trip to a settled Fulham side could extend their misery. Fulham (12th, 40pts) have been quietly consistent all season and a home win here effectively ends any lingering relegation anxiety while damaging Burnley's survival hopes significantly.",
    homeInjuries: [],
    awayInjuries: ['Squad availability unverified — check closer to kickoff for team news'],
    managerNote: null,
    flag: '⚠️ Burnley injury list not in source data. Assumes near-full squad but verify closer to kickoff.',
    homeLastMatch: {
      opponent: 'Everton',
      score: '2-0',
      result: 'W',
      lastMatchDate: '2026-03-14T15:00:00Z',
      lineup: [{ number: 1, name: 'Leno' }, { number: 5, name: 'Adarabioyo' }, { number: 23, name: 'Cuenca' }, { number: 27, name: 'Robinson' }, { number: 22, name: 'Tete' }, { number: 8, name: 'Palhinha' }, { number: 16, name: 'Reed' }, { number: 11, name: 'Jimenez' }, { number: 10, name: 'Mount' }, { number: 7, name: 'Pereira' }, { number: 23, name: 'Wilson' }],
      changes: 'Comfortable home win. Likely to start similar XI.',
    },
    awayLastMatch: {
      opponent: 'Newcastle',
      score: '0-3',
      result: 'L',
      lastMatchDate: '2026-03-08T15:00:00Z',
      lineup: [{ number: 1, name: 'Trafford' }, { number: 3, name: 'Cullen' }, { number: 6, name: 'Esteve' }, { number: 2, name: 'Harwood-Bellis' }, { number: 4, name: 'Flanagan' }, { number: 38, name: 'Barnes' }, { number: 11, name: 'Brownhill' }, { number: 12, name: 'Aronsson' }, { number: 7, name: 'Sordell' }, { number: 9, name: 'Lyle Foster' }, { number: 10, name: 'Nkunku' }],
      changes: 'Heavy defeat. Coach needs response. Desperate for points.',
    },
  },
  {
    id: 'man-city-crystal-palace',
    home: 'Man City',       homeId: 'man-city',       homeBadgePlId: 't43', homeColor: '#1c86cd',
    away: 'Crystal Palace', awayId: 'crystal-palace', awayBadgePlId: 't31', awayColor: '#1b458f',
    kickoff: '2026-03-21T15:00:00Z',
    kickoffLabel: 'Sat 21 Mar · 15:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'low',
    narrative: "Man City cannot afford dropped points in the title race — Pep Guardiola's side are 2nd (61pts), 9 points behind Arsenal, and must keep winning. Crystal Palace arrive fresh from a stunning 3-1 win at Tottenham last week, but face a very different proposition at the Etihad.",
    homeInjuries: ['Josko Gvardiol (ankle — out)', 'Mateo Kovacic (ankle — out)', 'Rico Lewis (ankle — doubt)'],
    awayInjuries: ['Eddie Nketiah (thigh — out)', 'Cheick Doucoure (knee — out)', 'Daniel Munoz (shoulder — doubt)'],
    managerNote: null,
    flag: '❌ POSTPONED — Man City vs Crystal Palace rescheduled due to Carabao Cup Final (Mar 22). New date TBD by Premier League. DO NOT PUBLISH in GW31 fixture list.',
    homeLastMatch: {
      opponent: 'West Ham',
      score: '3-0',
      result: 'W',
      lastMatchDate: '2026-03-14T15:00:00Z',
      lineup: [{ number: 1, name: 'Ederson' }, { number: 2, name: 'Walker' }, { number: 6, name: 'Akanji' }, { number: 4, name: 'Gvardiol' }, { number: 3, name: 'Gomez' }, { number: 17, name: 'De Bruyne' }, { number: 19, name: 'Rodri' }, { number: 20, name: 'Alvarez' }, { number: 25, name: 'Haaland' }, { number: 10, name: 'Grealish' }, { number: 7, name: 'Mahrez' }],
      changes: 'Dominant form. Gvardiol + Kovacic OUT for GW31.',
    },
    awayLastMatch: {
      opponent: 'Tottenham',
      score: '3-1',
      result: 'W',
      lastMatchDate: '2026-03-08T15:00:00Z',
      lineup: [{ number: 1, name: 'Henderson' }, { number: 2, name: 'Clyne' }, { number: 5, name: 'Guehi' }, { number: 4, name: 'Lerma' }, { number: 3, name: 'Mitchell' }, { number: 20, name: 'Eze' }, { number: 8, name: 'Sarr' }, { number: 10, name: 'Mateta' }, { number: 7, name: 'Nketiah' }, { number: 19, name: 'Kamada' }, { number: 11, name: 'Schlupp' }],
      changes: 'Clinical away win vs Spurs. Mateta in form.',
    },
  },
  {
    id: 'newcastle-sunderland',
    home: 'Newcastle',  homeId: 'newcastle',  homeBadgePlId: 't4',  homeColor: '#241f20',
    away: 'Sunderland', awayId: 'sunderland', awayBadgePlId: 't56', awayColor: '#eb172b',
    kickoff: '2026-03-22T12:00:00Z',
    kickoffLabel: 'Sun 22 Mar · 12:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'low',
    narrative: "The Tyne-Wear derby returns to St James' Park for the first time since Sunderland's promotion — the first PL Tyne-Wear derby in over a decade. Newcastle (9th, 42pts) need the points for a European push, while Sunderland's first taste of this fixture in years will be a defining moment for their promoted squad regardless of the result.",
    homeInjuries: ['Bruno Guimaraes (thigh — out until April)', 'Fabian Schär (ankle — out)', 'Lewis Miley (knee — out)', 'Emil Krafth (thigh — out)', 'Jacob Ramsey (suspension — availability for this game unverified)'],
    awayInjuries: ['Bertrand Traore (knee — up to 2 months out)', 'Mundle (thigh — out)', 'Ta Bi (ankle — out)', 'Brian Brobbey (groin — doubt, GW31 status unverified)', 'Dennis Cirkin (thigh — doubt, GW31 status unverified)'],
    managerNote: null,
    flag: null,
    homeLastMatch: {
      opponent: 'Chelsea',
      score: '2-1',
      result: 'W',
      lastMatchDate: '2026-03-08T15:00:00Z',
      lineup: [{ number: 1, name: 'Pope' }, { number: 2, name: 'Livramento' }, { number: 6, name: 'Schar' }, { number: 4, name: 'Burn' }, { number: 33, name: 'Hall' }, { number: 7, name: 'Almiron' }, { number: 34, name: 'Joelinton' }, { number: 14, name: 'Longstaff' }, { number: 17, name: 'Murphy' }, { number: 9, name: 'Wilson' }, { number: 10, name: 'Gordon' }],
      changes: 'Solid home win. Bruno out; Joelinton anchors midfield. Isak now at Liverpool — Wilson leads the line.',
    },
    awayLastMatch: {
      opponent: 'Ipswich',
      score: '1-2',
      result: 'L',
      lastMatchDate: '2026-03-09T15:00:00Z',
      lineup: [{ number: 1, name: 'Matzvarov' }, { number: 4, name: 'Coates' }, { number: 5, name: 'O\'Nien' }, { number: 2, name: 'Cirkin' }, { number: 23, name: 'Kalas' }, { number: 8, name: 'Dissing' }, { number: 16, name: 'Embleton' }, { number: 15, name: 'Gordon' }, { number: 10, name: 'Brobbey' }, { number: 9, name: 'Kulushevski' }, { number: 21, name: 'Neil' }],
      changes: 'Tough loss away. Derby energy needed vs Newcastle.',
    },
  },
  {
    id: 'aston-villa-west-ham',
    home: 'Aston Villa', homeId: 'aston-villa', homeBadgePlId: 't7',  homeColor: '#670e36',
    away: 'West Ham',    awayId: 'west-ham',    awayBadgePlId: 't21', awayColor: '#7a263a',
    kickoff: '2026-03-22T14:15:00Z',
    kickoffLabel: 'Sun 22 Mar · 14:15 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'top5',
    awayImportance: 'relegation',
    narrative: "Aston Villa's top-four place is under real pressure — 4th on 51pts, level on points with Man United — and they must win at Villa Park to maintain their edge. West Ham are in a relegation dog-fight at 17th (29pts), just 1 point above the drop zone. Three points here could prove season-defining for the Hammers. Jadon Sancho returns to availability after being ineligible against parent club Man Utd in GW30.",
    homeInjuries: ['Youri Tielemans (ankle — GW31 status unverified)', 'Boubacar Kamara (knee — GW31 status unverified)', 'Matty Cash (calf — GW31 status unverified)'],
    awayInjuries: ['Crysencio Summerville (lower leg — out, no return timeline)', 'Lukasz Fabianski (back — out)'],
    managerNote: "Jadon Sancho (Villa, on loan from Man United) was ineligible vs Man United in GW30 — returns to full availability for this fixture.",
    flag: null,
    homeLastMatch: {
      opponent: 'Man United',
      score: '1-3',
      result: 'L',
      lastMatchDate: '2026-03-15T15:00:00Z',
      lineup: [{ number: 1, name: 'Martinez' }, { number: 4, name: 'Cash' }, { number: 5, name: 'Konsa' }, { number: 2, name: 'Mings' }, { number: 3, name: 'Augustinsson' }, { number: 8, name: 'Luiz' }, { number: 6, name: 'Onana' }, { number: 7, name: 'Bailey' }, { number: 9, name: 'Watkins' }, { number: 19, name: 'Ramsey' }, { number: 10, name: 'Buendía' }],
      changes: 'Heavy loss vs United. Tielemans ankle concern. Sancho available vs West Ham.',
    },
    awayLastMatch: {
      opponent: 'Man City',
      score: '0-3',
      result: 'L',
      lastMatchDate: '2026-03-14T15:00:00Z',
      lineup: [{ number: 1, name: 'Fabianski' }, { number: 5, name: 'Cresswell' }, { number: 25, name: 'Coufal' }, { number: 6, name: 'Aguerd' }, { number: 3, name: 'Emerson' }, { number: 20, name: 'Alvarez' }, { number: 42, name: 'Kudus' }, { number: 8, name: 'Souček' }, { number: 7, name: 'Bowen' }, { number: 9, name: 'Fullkrug' }, { number: 14, name: 'Summerville' }],
      changes: 'Demolished at City. Summerville + Fabianski OUT for GW31. Desperate need.',
    },
  },
  {
    id: 'spurs-nottm-forest',
    home: 'Tottenham',    homeId: 'spurs',        homeBadgePlId: 't6',  homeColor: '#132257',
    away: 'Nottm Forest', awayId: 'nottm-forest', awayBadgePlId: 't17', awayColor: '#dd0000',
    kickoff: '2026-03-22T14:15:00Z',
    kickoffLabel: 'Sun 22 Mar · 14:15 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'relegation',
    awayImportance: 'relegation',
    narrative: "Arguably the biggest six-pointer of the season — two sides staring at the drop meet in a game that could define both their fates. Igor Tudor's Spurs are winless in 5 since his appointment (16th, 29pts), while Vítor Pereira's Forest are 18th (28pts) and already in the relegation zone. Both managers are under extreme pressure. One of them will leave this game with something to hold onto — the other could be looking at a manager change within days.",
    homeInjuries: ['James Maddison (ACL — season over)', 'Joao Palhinha (out)', 'Yves Bissouma (out)', 'Odobert (out)', 'Destiny Udogie (out)', 'Rodrigo Bentancur (out)', 'Mohammed Kudus (out)', 'Lucas Bergvall (out)', 'Dejan Kulusevski (out)', 'Ben Davies (out)', 'Van de Ven & Romero (suspended GW30 — GW31 availability TBC)'],
    awayInjuries: ['Chris Wood (knee — out)', 'Ndoye (out)', 'Willy Boly (knee — out)', 'Filippo Savona (knee — out)', 'John Victor (knee — out)', 'Jair Cunha (ankle — doubt)'],
    managerNote: "Igor Tudor (Spurs) — appointed Feb 14, 0 wins in 5 PL matches. Future in serious doubt. Spurs one point above relegation zone. Vítor Pereira (Forest) — appointed Feb 15, also winless in 5 PL matches since appointment.",
    flag: null,
    homeLastMatch: {
      opponent: 'Liverpool',
      score: '1-1',
      result: 'D',
      lastMatchDate: '2026-03-15T15:00:00Z',
      lineup: [{ number: 1, name: 'Vicario' }, { number: 4, name: 'van de Ven' }, { number: 6, name: 'Romero' }, { number: 2, name: 'Porro' }, { number: 3, name: 'Udogie' }, { number: 5, name: 'Sarr' }, { number: 8, name: 'Bissouma' }, { number: 20, name: 'Bentancur' }, { number: 7, name: 'Kulusevski' }, { number: 27, name: 'Richarlison' }, { number: 10, name: 'Madlener' }],
      changes: 'Richarlison 90\' equaliser rescues point. Defensive crisis ongoing.',
    },
    awayLastMatch: {
      opponent: 'Chelsea',
      score: '0-2',
      result: 'L',
      lastMatchDate: '2026-03-12T15:00:00Z',
      lineup: [{ number: 1, name: 'Sels' }, { number: 5, name: 'Yacob' }, { number: 4, name: 'Ajayi' }, { number: 2, name: 'Aurier' }, { number: 3, name: 'Lodi' }, { number: 8, name: 'Henrichs' }, { number: 7, name: 'Gibbs-White' }, { number: 6, name: 'Dominguez' }, { number: 11, name: 'Awoniyi' }, { number: 9, name: 'Hudson-Odoi' }, { number: 10, name: 'Johnson' }],
      changes: 'Pereira struggling. Desperate need for points vs struggling Spurs.',
    },
  },
];

// ─── TOP SCORERS (GW30 / MD29) — Approved by Referee (2026-03-17 03:35) ──────
// Scout submission fact-checked against official sources. Kane/Bundesliga rejected (scope).
const TOP_SCORERS_DATA = [
  {
    id: 'haaland-gw30',
    rank: 1,
    player: 'Erling Haaland',
    club: 'Manchester City',
    clubBadge: '🩵',
    league: 'premier-league',
    leagueName: 'Premier League',
    position: 'ST',
    goals: 12,
    apps: 29,
    goalsPerGame: (12 / 29).toFixed(2),
    detail: 'Leads the Premier League scoring charts by a wide margin. 12 goals in 29 appearances (GW30 season snapshot). Clinical finishing and consistent game time have made him the standout striker in English football this season.',
    avatar: '🧑',
    tag: 'prem-topscorer',
    date: 'Mar 17, 2026',
    source: 'https://www.premierleague.com/stats/top-scorers',
    kickoffLabel: 'Tue 17 Mar · GW30 (GMT+8)',
  },
  {
    id: 'mbappe-gw30',
    rank: 2,
    player: 'Kylian Mbappé',
    club: 'Real Madrid',
    clubBadge: '⚪',
    league: 'la-liga',
    leagueName: 'La Liga',
    position: 'ST',
    goals: 9,
    apps: 23,
    goalsPerGame: (9 / 23).toFixed(2),
    detail: '9 La Liga goals in 23 La Liga appearances (MD29 snapshot). Mbappé has been the standout attacking force for Real Madrid in La Liga play this season, despite missing recent fixtures with a knee injury (last 3 weeks).',
    avatar: '🧑',
    tag: 'laliga-topscorer',
    date: 'Mar 17, 2026',
    source: 'https://www.laliga.es/en/rankings/scorers',
    kickoffLabel: 'Tue 17 Mar · MD29 (GMT+8)',
  },
];

// ─── EUROPEAN RESULTS & NEWS (Mar 16, 2026) ──────────────────────────────────
// La Liga (MD29) + Bundesliga (MD26) — Approved by Referee
const EUROPEAN_NEWS = [
  // ── Premier League ──
  {
    type: 'suspension',
    league: 'premier-league',
    leagueName: 'Premier League',
    title: 'Wolves Trio on 9 Yellows — One More = 2-Match Ban',
    detail: 'João Gomes (M), André (M), and Yerson Mosquera (D) are all on 9 yellow cards for the season. Under PL rules, reaching 10 yellows by GW32 triggers an automatic two-match suspension. Wolves are bottom (16pts) and 13 points from safety — losing key midfielders or their CB to bans would be catastrophic.',
    date: 'Mar 16, 2026',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
    impact: 'high',
  },
  // ── La Liga Results ──
  {
    type: 'result',
    league: 'la-liga',
    leagueName: 'La Liga',
    title: 'Barcelona 5-2 Sevilla (MD29)',
    detail: 'Raphinha hat-trick (9\' pen, 21\' pen, 51\'). Dani Olmo (38\'), Cancelo (60\'). Sevilla: Oso 45+4\', Sow 90+2\'. Emphatic home win at the Spotify Camp Nou on Mar 15.',
    date: 'Mar 15, 2026',
    source: 'https://www.fcbarcelona.com/en/football/first-team/news/2026/03/15/barcelona-sevilla-5-2',
    impact: 'high',
  },
  {
    type: 'result',
    league: 'la-liga',
    leagueName: 'La Liga',
    title: 'Real Madrid 4-1 Elche (MD29)',
    detail: 'Rüdiger (39\'), Valverde (44\'), Huijsen (66\'), Güler (89\'). Elche reply: own goal (85\'). Mbappe absent (knee); targeting UCL 2nd leg vs Man City (Mar 17).',
    date: 'Mar 14, 2026',
    source: 'https://www.espn.com/soccer/match/_/gameId/real-madrid-elche-md29',
    impact: 'medium',
  },
  {
    type: 'transfer',
    league: 'la-liga',
    leagueName: 'La Liga',
    title: 'Griezmann Staying at Atlético — Confirmed',
    detail: 'Atlético football director Mateu Alemany: "He has a contract, he\'s going to stay with us." Antoine Griezmann\'s future confirmed ahead of the Madrid derby (Mar 22).',
    date: 'Mar 2026',
    source: 'https://www.as.com/futbol/la-liga/griezmann-atletico-madrid-stays-alemany/',
    impact: 'medium',
  },
  // ── Bundesliga Results ──
  {
    type: 'result',
    league: 'bundesliga',
    leagueName: 'Bundesliga',
    title: 'Leverkusen 1-1 Bayern (MD26) — Nine-Man Bayern Hold On',
    detail: 'Aleix García (6\') opened for Leverkusen. Luis Díaz equalised (69\'). Bayern had two goals disallowed. Finished with 9 men: Nicolas Jackson (straight red, 42\') and Luis Díaz (yellow-red, 84\'). Leverkusen\'s late winner disallowed offside. Bayern face Atalanta UCL 2nd leg with all three senior GKs out — Neuer (calf), Urbig (concussion), Ulreich (adductor tear).',
    date: 'Mar 14, 2026',
    source: 'https://www.bundesliga.com/en/bundesliga/news/leverkusen-bayern-matchday-26',
    impact: 'high',
  },
];
