// ===== PitchIQ — app.js =====
// Data last updated: Mar 14, 2026 — Sources: NBC Sports, BBC Sport, The Athletic, Sky Sports, Wikipedia

// ─── DATA ────────────────────────────────────────────────────────────────────

// INJURIES & SUSPENSIONS — Real EPL GW30 data (Mar 14–15, 2026)
const INJURIES_DATA = [
  {
    type: 'injury',
    player: 'Alexander Isak',
    avatar: '🧑',
    club: 'Liverpool',
    clubBadge: '❤️',
    position: 'ST',
    detail: 'Broken leg — OUT for the remainder of the 2025-26 season. The £125m summer signing from Newcastle has barely featured since arriving at Anfield. Surgery was successful but Slot confirmed he will not return this campaign.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  {
    type: 'injury',
    player: 'James Maddison',
    avatar: '🧑',
    club: 'Tottenham',
    clubBadge: '⚪',
    position: 'CAM',
    detail: 'Torn ACL — season over. Carried off in tears earlier in the campaign. One of 13 Spurs players either out or a doubt for GW30 — the worst injury crisis at any PL club this season.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
  {
    type: 'suspension',
    player: 'Pedro Neto',
    avatar: '🧑',
    club: 'Chelsea',
    clubBadge: '💙',
    position: 'RW',
    detail: 'Two-match ban confirmed by the FA on Mar 13. Red card for dissent vs Arsenal (Mar 1) plus an additional one-match ban for misconduct — failing to leave the pitch promptly and using abusive language toward officials. Also fined £70,000.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Newcastle (GW30) + GW31',
    source: 'https://www.nytimes.com/athletic/7115445/2026/03/13/chelsea-pedro-neto-red-card-ban-arsenal/',
  },
  {
    type: 'injury',
    player: 'Bertrand Traore',
    avatar: '🧑',
    club: 'Sunderland',
    clubBadge: '🔴',
    position: 'LW',
    detail: 'Knee injury sustained in Sunderland\'s win at Leeds on Mar 3. Could miss up to two months. Brian Brobbey and Dennis Cirkin have returned to training ahead of GW30 vs Brighton.',
    impact: 'medium',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Brighton (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'doubt',
    player: 'Martin Odegaard',
    avatar: '🧑',
    club: 'Arsenal',
    clubBadge: '🔴',
    position: 'CAM',
    detail: 'Knock — doubt for GW30 vs Everton. Picked up after the Champions League draw at Bayer Leverkusen on Wednesday. Arteta says he will be assessed before selection. Leandro Trossard also a doubt.',
    impact: 'medium',
    date: 'Mar 14, 2026',
    matchAffected: 'vs Everton (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'injury',
    player: 'Crysencio Summerville',
    avatar: '🧑',
    club: 'West Ham',
    clubBadge: '⚒️',
    position: 'RW',
    detail: 'Lower leg injury — ruled out with no return timeline before Man City\'s visit. The Dutch winger scored last week and is a significant miss for relegation-threatened West Ham. Ollie Scarles and Adama Traoré assessed.',
    impact: 'high',
    date: 'Mar 14, 2026',
    matchAffected: 'vs Man City (GW30)',
    source: 'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o',
  },
  {
    type: 'suspension',
    player: 'Micky van de Ven',
    avatar: '🧑',
    club: 'Tottenham',
    clubBadge: '⚪',
    position: 'CB',
    detail: 'Serving a one-match suspension following his red card in the 3-1 home defeat to Crystal Palace. Misses the Liverpool trip at Anfield on Sunday. Cristian Romero also suspended — Spurs travel to Anfield without two first-choice centre-backs.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'vs Liverpool (GW30)',
    source: 'https://www.sportsmole.co.uk/football/spurs/injury-news/injuries-and-suspensions/van-de-ven-romero-palhinha-udogie-kudus-latest-spurs-injury-list-for-liverpool-clash_593655.html',
  },
  {
    type: 'injury',
    player: 'Levi Colwill',
    avatar: '🧑',
    club: 'Chelsea',
    clubBadge: '💙',
    position: 'CB',
    detail: 'Torn ACL — surgery confirmed, out for the remainder of the season. A significant blow to Chelsea\'s defensive stability under new manager Liam Rosenior. Estevao (hamstring) also OUT, and Mykhailo Mudryk serving a doping suspension.',
    impact: 'high',
    date: 'Mar 13, 2026',
    matchAffected: 'All remaining GWs',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
];

// TRANSFERS — Real confirmed EPL transfers 2025-26 season
const TRANSFERS_DATA = [
  {
    type: 'transfer-in',
    player: 'Alexander Isak',
    avatar: '🧑',
    fromClub: 'Newcastle United',
    fromBadge: '⚫',
    toClub: 'Liverpool',
    toBadge: '❤️',
    fee: '£125m',
    position: 'ST',
    detail: 'British transfer record at the time of signing in summer 2025. Isak scored 23 PL goals for Newcastle in 2024-25. The move has been labelled a "farce" by pundits — a broken leg has kept him sidelined for most of his debut Anfield season. Expected to return before end of campaign.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://en.wikipedia.org/wiki/Alexander_Isak',
  },
  {
    type: 'transfer-in',
    player: 'Florian Wirtz',
    avatar: '🧑',
    fromClub: 'Bayer Leverkusen',
    fromBadge: '🔴',
    toClub: 'Liverpool',
    toBadge: '❤️',
    fee: '~£116m',
    position: 'AM',
    detail: 'German international signed in summer 2025. Adaptation slower than expected — only 1 PL goal before Christmas. Now showing form: 6 goals and 8 assists across 37 appearances in all competitions. Liverpool have NO plans to sell despite Real Madrid interest.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://en.wikipedia.org/wiki/Florian_Wirtz',
  },
  {
    type: 'transfer-in',
    player: 'Jack Grealish',
    avatar: '🧑',
    fromClub: 'Man City',
    fromBadge: '🩵',
    toClub: 'Everton',
    toBadge: '🔵',
    fee: 'Season Loan (£225k/wk wages)',
    position: 'LW',
    detail: 'Season-long loan confirmed Aug 12, 2025. Grealish looked revitalised at Everton\'s new Hill Dickinson Stadium before a January ankle injury ended his season. Permanent transfer now reportedly more likely given his attitude and Friedkin Group\'s increased summer budget.',
    impact: 'medium',
    date: 'Aug 12, 2025',
    window: 'Season Loan',
    source: 'https://en.wikipedia.org/wiki/Jack_Grealish',
  },
  {
    type: 'transfer-in',
    player: 'Patrick Dorgu',
    avatar: '🧑',
    fromClub: 'Lecce',
    fromBadge: '🟡',
    toClub: 'Man United',
    toBadge: '🔴',
    fee: '~£37m',
    position: 'LB/LW',
    detail: 'Danish full-back/winger signed from Serie A. Currently injured (thigh, OUT for GW30). Michael Carrick has deployed Matheus Cunha on the left flank in his absence. Man United eyeing a further left-back signing in summer (Nico Williams linked at €80m).',
    impact: 'medium',
    date: 'Jan 2025',
    window: 'Permanent',
    source: 'https://en.wikipedia.org/wiki/Patrick_Dorgu',
  },
  {
    type: 'transfer-in',
    player: 'Joao Pedro',
    avatar: '🧑',
    fromClub: 'Brighton',
    fromBadge: '🦅',
    toClub: 'Chelsea',
    toBadge: '💙',
    fee: 'Undisclosed',
    position: 'ST',
    detail: 'Hitting top form under Liam Rosenior. Scored a hat-trick and added an assist in GW29 (19 FPL points — his best haul of the season). The most transferred-in FPL player ahead of GW30. The Guardian noted Rosenior has "unlocked" him.',
    impact: 'high',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://www.theguardian.com/football/2026/mar/10/joao-pedro-shining-chelsea-psg-champions-league',
  },
  {
    type: 'transfer-in',
    player: 'Estevao',
    avatar: '🧑',
    fromClub: 'Palmeiras',
    fromBadge: '🇧🇷',
    toClub: 'Chelsea',
    toBadge: '💙',
    fee: 'Pre-contract (signed 2024)',
    position: 'RW',
    detail: 'Highly-rated Brazilian winger joined Chelsea on turning 18 in summer 2025. Pre-contract agreed in 2024. Currently out with a hamstring injury (GW30). Rosenior confirmed he could be available for the Champions League second leg vs PSG next week.',
    impact: 'medium',
    date: 'Summer 2025',
    window: 'Permanent',
    source: 'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates',
  },
];

// MANAGER CHANGES — Real EPL 2025-26 managerial changes (most recent/impactful 4)
const MANAGERS_DATA = [
  {
    club: 'Manchester United',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Michael Carrick',
    previousManager: 'Ruben Amorim',
    reason: 'Amorim sacked Jan 5, 2026 after dispute with Director of Football Jason Wilcox over recruitment. Club were 6th. Darren Fletcher served as interim for two games.',
    style: 'Flexible formation, high-energy pressing, player-led culture',
    detail: 'Carrick appointed Jan 13, 2026. Won 5 of his first 6 league games — a remarkable turnaround. Roberto De Zerbi is on the shortlist for the permanent role but Carrick is making a strong case. Installed Steve Holland and Jonathan Woodgate as coaches. Man Utd 3rd, 51 pts.',
    impact: 'high',
    date: 'Jan 13, 2026',
    matchesInCharge: 9,
    source: 'https://www.bbc.com/sport/football/articles/cpv812n1w7vo',
  },
  {
    club: 'Tottenham Hotspur',
    badge: '⚪',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Igor Tudor',
    previousManager: 'Thomas Frank',
    reason: 'Frank sacked Feb 11, 2026 after just 2 wins in 17 league games. Club sat 16th. Frank had joined from Brentford earlier in the season.',
    style: 'Defensive, counter-attack, rigid positional play',
    detail: 'Tudor appointed Feb 14, 2026 — 5 matches, zero wins. Spurs lost 3-1 to Crystal Palace (GW30) and were thrashed 5-2 by Atlético Madrid in the Champions League. Tudor\'s future is in serious doubt but he remains in charge as of Mar 15, 2026. Spurs sit one point off the relegation zone heading into the Liverpool trip at Anfield.',
    impact: 'high',
    date: 'Feb 14, 2026',
    matchesInCharge: 5,
    source: 'https://www.footballinsider247.com/igor-tudor-is-to-do-something-no-premier-league-manager-has-ever-done-amid-tottenham-decision/',
  },
  {
    club: 'Nottingham Forest',
    badge: '🌳',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Vítor Pereira',
    previousManager: 'Sean Dyche',
    reason: 'Dyche sacked Feb 12, 2026 after a goalless home draw with bottom-side Wolves left Forest 17th — their fourth managerial change of the season.',
    style: 'Defensive organisation, direct transitions, similar profile to Nuno',
    detail: 'Pereira appointed Feb 15, 2026 on an 18-month deal. Previously managed Wolves earlier this season. The Athletic reports significant changes to training and on-pitch structure. Forest have gone 5 PL matches without a win and sit 17th — 3 points from safety.',
    impact: 'high',
    date: 'Feb 15, 2026',
    matchesInCharge: 5,
    source: 'https://www.theguardian.com/football/2026/feb/15/nottingham-forest-confirm-vitor-pereira-as-head-coach',
  },
  {
    club: 'Chelsea',
    badge: '💙',
    league: 'premier-league',
    leagueName: 'Premier League',
    newManager: 'Liam Rosenior',
    previousManager: 'Enzo Maresca',
    reason: 'Maresca departed Jan 1, 2026 — one win in 7 league games. Breakdown in relations with ownership over club structure. Club sat 5th.',
    style: 'Possession-based, unlocking wide forwards, high player trust',
    detail: 'Rosenior appointed Jan 6, 2026. Has unlocked Joao Pedro (hat-trick GW29) and rebuilt Cole Palmer\'s confidence. Cole Palmer has scored 5 goals and 1 assist in the last 6 GWs (45 FPL pts since GW25 — most of any midfielder). Chelsea 5th, 48 pts, Champions League in sight.',
    impact: 'high',
    date: 'Jan 6, 2026',
    matchesInCharge: 11,
    source: 'https://www.theguardian.com/football/2026/mar/10/joao-pedro-shining-chelsea-psg-champions-league',
  },
];

// RULES & VAR — Confirmed for 2025-26 Premier League season
const RULES_DATA = [
  {
    title: 'Semi-Automated Offside Technology (SAOT) — First Full PL Season',
    icon: '📏',
    category: 'Technology',
    league: ['Premier League'],
    detail: 'SAOT was introduced at the end of 2024-25 (Apr 12, 2025) and is now in full operation for the entire 2025-26 Premier League season — the first league in the world to run it for a full campaign. Average offside decision time has dropped from over 4 minutes to under 40 seconds. Precise limb-tracking data determines marginal calls.',
    predictionNote: 'Faster offside rulings mean fewer extended stoppages. Marginally more close-range goals likely to stand — slight upward pressure on goals markets vs pre-SAOT seasons.',
    date: 'Season start Aug 2025',
    effective: 'All 380 Premier League matches 2025-26',
    source: 'https://en.wikipedia.org/wiki/2025%E2%80%9326_Premier_League',
  },
];

// FORM & STATS — Real EPL 2025-26 standings (as of GW29, source: NBC Sports Mar 13, 2026)
const FORM_DATA = [
  {
    team: 'Arsenal',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'D', 'W', 'W'],
    played: 31, wins: 21, draws: 7, losses: 3,
    gf: 61, ga: 22,
    cleanSheets: 12,
    topScorer: 'Bukayo Saka (16 shots since Jan, top 2 at club)',
    nextMatch: 'GW31 TBC',
    rank: 1,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Manchester City',
    badge: '🩵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'L', 'W', 'W'],
    played: 30, wins: 18, draws: 7, losses: 5,
    gf: 60, ga: 28,
    cleanSheets: 10,
    topScorer: 'Erling Haaland — 22 PL goals (league top scorer)',
    nextMatch: 'GW31 TBC',
    rank: 2,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Chelsea',
    badge: '💙',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'W', 'L'],
    played: 30, wins: 13, draws: 9, losses: 8,
    gf: 43, ga: 30,
    cleanSheets: 9,
    topScorer: 'Joao Pedro — hat-trick GW29, most transferred-in FPL',
    nextMatch: 'GW31 TBC',
    rank: 5,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Liverpool',
    badge: '❤️',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'L', 'W'],
    played: 29, wins: 13, draws: 5, losses: 11,
    gf: 40, ga: 44,
    cleanSheets: 7,
    topScorer: 'Florian Wirtz — 6 goals, 8 assists (all comps)',
    nextMatch: 'GW31 TBC',
    rank: 6,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Tottenham Hotspur',
    badge: '⚪',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'L', 'L', 'L', 'L'],
    played: 30, wins: 7, draws: 8, losses: 15,
    gf: 30, ga: 36,
    cleanSheets: 5,
    topScorer: 'No consistent scorer — worst form in PL in 2026',
    nextMatch: 'GW31 TBC',
    rank: 16,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Wolves',
    badge: '🐺',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'L', 'L', 'D', 'L'],
    played: 30, wins: 3, draws: 7, losses: 20,
    gf: 22, ga: 52,
    cleanSheets: 4,
    topScorer: 'Various — winless run, bottom of PL',
    nextMatch: 'GW31 TBC',
    rank: 20,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Manchester United',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'W', 'D', 'W'],
    played: 29, wins: 16, draws: 5, losses: 8,
    gf: 49, ga: 36,
    cleanSheets: 8,
    topScorer: 'Erling Haaland — 22 PL goals (league top scorer)',
    nextMatch: 'GW31 TBC',
    rank: 3,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Aston Villa',
    badge: '🟣',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'W', 'L'],
    played: 29, wins: 15, draws: 6, losses: 8,
    gf: 56, ga: 39,
    cleanSheets: 9,
    topScorer: 'Ollie Watkins — 8 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 4,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Brentford',
    badge: '🐝',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'L', 'W', 'D', 'W'],
    played: 29, wins: 13, draws: 5, losses: 11,
    gf: 44, ga: 40,
    cleanSheets: 7,
    topScorer: 'Dango Ouattara — top contributor (Bryan Mbeumo continues to be key player)',
    nextMatch: 'GW31 TBC',
    rank: 7,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Fulham',
    badge: '⬜',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'W', 'D', 'L', 'W'],
    played: 30, wins: 12, draws: 7, losses: 11,
    gf: 43, ga: 43,
    cleanSheets: 6,
    topScorer: 'Raul Jimenez — 8 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 12,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Bournemouth',
    badge: '🍒',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'W', 'D', 'W', 'D'],
    played: 30, wins: 12, draws: 6, losses: 12,
    gf: 39, ga: 44,
    cleanSheets: 8,
    topScorer: 'Evanilson — 6 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 10,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Brighton',
    badge: '🌊',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'W', 'W'],
    played: 30, wins: 10, draws: 10, losses: 10,
    gf: 39, ga: 36,
    cleanSheets: 6,
    topScorer: 'Yankuba Minteh — top scorer',
    nextMatch: 'GW31 TBC',
    rank: 11,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Newcastle',
    badge: '⚫',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'D', 'W', 'L', 'W'],
    played: 30, wins: 12, draws: 7, losses: 11,
    gf: 43, ga: 35,
    cleanSheets: 7,
    topScorer: 'Anthony Gordon — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 9,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Crystal Palace',
    badge: '🦅',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'W', 'D', 'L', 'W'],
    played: 29, wins: 12, draws: 4, losses: 13,
    gf: 37, ga: 46,
    cleanSheets: 7,
    topScorer: 'Jean-Philippe Mateta — 8 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 14,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Everton',
    badge: '🔵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'D', 'L', 'W', 'L'],
    played: 30, wins: 10, draws: 7, losses: 13,
    gf: 36, ga: 40,
    cleanSheets: 6,
    topScorer: 'Kiernan Dewsbury-Hall — 6 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 8,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Sunderland',
    badge: '🔴',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['W', 'L', 'D', 'L', 'L'],
    played: 30, wins: 10, draws: 10, losses: 10,
    gf: 39, ga: 36,
    cleanSheets: 5,
    topScorer: 'Brian Brobbey — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 13,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Leeds United',
    badge: '🟡',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'L', 'D', 'L', 'L'],
    played: 29, wins: 7, draws: 10, losses: 12,
    gf: 29, ga: 37,
    cleanSheets: 4,
    topScorer: 'Dominic Calvert-Lewin — 10 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 15,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'West Ham',
    badge: '⚒️',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'L', 'D', 'L', 'D'],
    played: 30, wins: 7, draws: 8, losses: 15,
    gf: 28, ga: 43,
    cleanSheets: 4,
    topScorer: 'Crysencio Summerville — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 17,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Nottm Forest',
    badge: '🌳',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['D', 'L', 'D', 'D', 'L'],
    played: 29, wins: 7, draws: 7, losses: 15,
    gf: 29, ga: 48,
    cleanSheets: 4,
    topScorer: 'Morgan Gibbs-White — 7 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 18,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
  {
    team: 'Burnley',
    badge: '🔵',
    league: 'premier-league',
    leagueName: 'Premier League',
    form: ['L', 'D', 'L', 'L', 'D'],
    played: 30, wins: 4, draws: 8, losses: 18,
    gf: 21, ga: 55,
    cleanSheets: 3,
    topScorer: 'Lyle Foster — 5 PL goals',
    nextMatch: 'GW31 TBC',
    rank: 19,
    source: 'https://www.nbcsports.com/soccer/news/premier-league-2025-26-table-teams-standings-for-the-new-season',
  },
];

// ─── EPL TEAMS DATA ──────────────────────────────────────────────────────────
// Real news only — Sources: NBC Sports, BBC Sport, The Athletic (Mar 13–14, 2026)

const EPL_TEAMS = [
  { id:'arsenal', name:'Arsenal', badge:'🔴', news:[
    { type:'injury', title:'Mikel Merino — OUT (Ankle)', subtitle:'🔴 Arsenal · CM', body:'Ankle injury — out for GW30 vs Everton. Odegaard (knock) and Trossard (unspecified) are doubts. Arsenal top the table with 67pts (20W-7D-3L).', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'aston-villa', name:'Aston Villa', badge:'🟣', news:[
    { type:'injury', title:'Tielemans & Kamara — Both OUT', subtitle:'🟣 Aston Villa · CM/CDM', body:'Tielemans (ankle) and Kamara (knee) both out for GW30 vs Man United. Matty Cash (calf) a doubt. Villa 4th with 51pts. Jadon Sancho ineligible vs parent club Man United.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'bournemouth', name:'Bournemouth', badge:'🍒', news:[
    { type:'injury', title:'Lewis Cook & Kluivert — OUT', subtitle:'🍒 Bournemouth · CM/LW', body:'Cook (thigh) and Kluivert (knee) both out. Ben Doak (hamstring) back in training but unlikely to feature. Bournemouth 9th, 41pts.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'brentford', name:'Brentford', badge:'🐝', news:[
    { type:'injury', title:'Six Long-Term Absentees', subtitle:'🐝 Brentford · Squad', body:'Hickey (thigh), Janelt (ankle), Rico Henry (thigh), Milambo (knee), Fabio Carvalho (ACL) and Dasilva (knee) all out. Despite injuries, Brentford are 7th with 44pts.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'brighton', name:'Brighton', badge:'🌊', news:[
    { type:'injury', title:'Mitoma — Doubt for GW30', subtitle:'🌊 Brighton · LW', body:'Mitoma (ankle) forced off at half-time vs Arsenal on Mar 4. Doubt for Sunderland away. Webster (knee) and Tzimas (unspecified) confirmed out.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'burnley', name:'Burnley', badge:'🔵', news:[
  ]},
  { id:'chelsea', name:'Chelsea', badge:'💙', news:[
    { type:'contract', title:'Reece James Signs New 6-Year Contract', subtitle:'💙 Chelsea · RB', body:"Chelsea captain Reece James committed his future to Stamford Bridge until June 2032. Described as Chelsea's most important deal of 2026 — massive boost amid defensive injury woes.", impact:'high', date:'Mar 13, 2026', tag:'contract', isNew:true, source:'https://www.footballtransfers.com/en/transfer-news/uk-premier-league/2026/03/chelsea-news-reece-james-new-contract-most-important-deal-2026' },
    { type:'suspension', title:'Pedro Neto — 2-Match Ban & £70k Fine', subtitle:'💙 Chelsea · RW', body:'Two-match ban confirmed Mar 13. Red card for dissent vs Arsenal (Mar 1) + misconduct. Misses Newcastle (GW30) and GW31.', impact:'high', date:'Mar 13, 2026', tag:'suspension', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
    { type:'injury', title:'Colwill — Torn ACL, Season Over', subtitle:'💙 Chelsea · CB', body:'Season-ending ACL. Estevao (hamstring) also out. Mudryk serving doping suspension. Rosenior unlocked Joao Pedro (hat-trick GW29). Chelsea 5th, 48pts.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'crystal-palace', name:'Crystal Palace', badge:'🦅', news:[
    { type:'injury', title:'Nketiah & Doucoure — Both OUT', subtitle:'🦅 Crystal Palace · Attack/Mid', body:'Nketiah (thigh) and Doucoure (knee) both out. Munoz (shoulder) a doubt. Palace beat Spurs 3-1 last GW — Van de Ven red card was pivotal.', impact:'medium', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'everton', name:'Everton', badge:'🔵', news:[
  ]},
  { id:'fulham', name:'Fulham', badge:'⬜', news:[
  ]},
  { id:'liverpool', name:'Liverpool', badge:'❤️', news:[
    { type:'injury', title:'Isak — Broken Leg, Season Over', subtitle:'❤️ Liverpool · ST', body:'£125m summer signing out for the season. Endo (ankle), Bradley (knee) also out. Alisson and Chiesa doubts vs Spurs at Anfield.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'man-city', name:'Man City', badge:'🩵', news:[
    { type:'injury', title:'Gvardiol & Kovacic — Both OUT', subtitle:'🩵 Man City · CB/CM', body:'Gvardiol (ankle) and Kovacic (ankle) both out. Rico Lewis (ankle) a doubt. City travel to West Ham — strong favourites.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'man-utd', name:'Man United', badge:'🔴', news:[
    { type:'transfer', title:'Hojølund to Napoli Confirmed — €50m Deal', subtitle:'🔴 Man United · Transfer', body:'Napoli confirmed they will trigger their obligation to buy Rasmous Hojølund regardless of CL qualification. Romano called it \u201ca formality.\u201d United receive €50m total (€44m buy + €6m loan fee) to fund summer spending.', impact:'high', date:'Mar 14, 2026', tag:'transfer', isNew:true, source:'https://www.football365.com/news/man-utd-hojlund-exit-confirmed-director-transfer-sealed' },

    { type:'manager', title:'Carrick Appointed — 5W in First 6 Games', subtitle:'🔴 Man United · Manager', body:'Amorim sacked Jan 5. Carrick appointed Jan 13 — 5W in first 6 league games. Man United 3rd, 51pts. De Zerbi linked for permanent role.', impact:'high', date:'Jan 13, 2026', tag:'manager', source:'https://www.bbc.com/sport/football/articles/cpv812n1w7vo' },
    { type:'injury', title:'De Ligt — May Miss Rest of Season (Back)', subtitle:'🔴 Man United · CB', body:'Persistent back problem puts De Ligt at serious risk of missing the rest of the season — no training since early December. Martinez (calf) and Dorgu (thigh) also out. Mazraoui (foot) and Mount (knock) doubts.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'newcastle', name:'Newcastle', badge:'⚫', news:[
    { type:'injury', title:'Bruno Out Until April; Ramsey Suspended', subtitle:'⚫ Newcastle · Key Players', body:'Bruno Guimaraes (thigh) out until April — longer than initially feared. Jacob Ramsey suspended until Mar 22 (accumulated yellows). Fabian Schär (ankle), Lewis Miley (knee) and Emil Krafth (thigh) also sidelined.', isNew:true, impact:'high', date:'Mar 13, 2026', tag:'injury', source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'nottm-forest', name:'Nottm Forest', badge:'🌳', news:[
    { type:'injury', title:'Six Players OUT Including Chris Wood', subtitle:'🌳 Forest · Squad', body:'Ndoye, Ortega (calf), Boly (knee), Savona (knee), John Victor (knee) and Wood (knee) all out. Jair Cunha (ankle) a doubt.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'leeds', name:'Leeds United', badge:'🟡', news:[
    { type:'injury', title:'Okafor — Doubt vs Crystal Palace', subtitle:'🟡 Leeds · FW', body:'Noah Okafor fitness doubt for GW30 at Crystal Palace. Calvert-Lewin expected to be available. Leeds 3pts above relegation after 4 PL games without a win. Beat Norwich 3-0 in FA Cup last time out.', impact:'high', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://motleedsnews.com/leeds-united/leeds-united-injuries/crystal-palace-vs-leeds-united-injury-latest-as-four-players-could-miss-out/' },
  ]},
  { id:'spurs', name:'Tottenham', badge:'⚪', news:[
    { type:'suspension', title:'Van de Ven & Romero Suspended + 11 Others OUT', subtitle:'⚪ Spurs · Defence', body:'Both first-choice CBs suspended for Liverpool away. Plus Maddison (ACL), Palhinha, Bissouma, Odobert, Udogie, Bentancur, Kudus, Bergvall, Kulusevski, Davies all out — 13 unavailable total.', impact:'high', date:'Mar 13, 2026', tag:'suspension', isNew:true, source:'https://www.sportsmole.co.uk/football/spurs/injury-news/injuries-and-suspensions/van-de-ven-romero-palhinha-udogie-kudus-latest-spurs-injury-list-for-liverpool-clash_593655.html' },
  ]},
  { id:'west-ham', name:'West Ham', badge:'⚒️', news:[
    { type:'injury', title:'Summerville & Fabianski — Both OUT vs Man City', subtitle:'⚒️ West Ham · Key Players', body:'Crysencio Summerville (lower leg) out with no return timeline. Fabianski (back) also unavailable. West Ham battling relegation — 2 points from safety.', impact:'high', date:'Mar 14, 2026', tag:'injury', isNew:true, source:'https://www.bbc.co.uk/sport/articles/clyv7dk02g2o' },
  ]},
  { id:'wolves', name:'Wolves', badge:'🐺', news:[
    { type:'injury', title:'Enso Medina — OUT (Knee)', subtitle:'🐺 Wolves · Forward', body:'Enso Medina (knee) out. Wolves in crisis: 19-match winless run, bottom of table with 3W-7D-20L. 9 points from safety with 8 games left.', impact:'high', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
  { id:'sunderland', name:'Sunderland', badge:'🔴', news:[
    { type:'injury', title:'Traore, Mundle & Ta Bi — All OUT', subtitle:'🔴 Sunderland · Attack', body:'Traore (knee), Mundle (thigh) and Ta Bi (ankle) all out. Brobbey (groin) and Cirkin (thigh) doubts. Sunderland back in PL for first time since 2017.', impact:'medium', date:'Mar 13, 2026', tag:'injury', isNew:true, source:'https://www.nbcsports.com/soccer/news/premier-league-injury-table-2025-26-season-club-by-club-injuries-suspensions-latest-updates' },
  ]},
];

// ─── MATCH PREVIEWS DATA — GW31 (Mar 16–22, 2026) ────────────────────────────
// Sources: Sky Sports fixtures, data.js injuries, NBC Sports standings
// ⚠️ Man City vs Crystal Palace kickoff UNVERIFIED (may be postponed — check closer to date)

// PREVIEWS_DATA — fact-checked by Referee (2026-03-15)
const PREVIEWS_DATA = [
  {
    id: 'brentford-wolves',
    home: 'Brentford', homeId: 'brentford', homeBadgePlId: 't94', homeColor: '#e30613',
    away: 'Wolves',    awayId: 'wolves',    awayBadgePlId: 't39', awayColor: '#c8a84b',
    kickoff: '2026-03-16T20:00:00Z',
    kickoffLabel: 'Mon 16 Mar · 20:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'top5',
    awayImportance: 'relegation',
    narrative: 'Brentford sit 7th (44pts) and are pushing for a Europa League spot — a remarkable achievement given their raft of long-term absentees. For Wolves — bottom of the table with just 3 wins all season and a goal difference of -30 — this is as close to a must-win as a side with 16pts gets with 8 games left.',
    homeInjuries: ['Aaron Hickey (thigh — long-term)', 'Vitaly Janelt (ankle — long-term)', 'Rico Henry (thigh — long-term)', 'Antoni Milambo (knee — long-term)', 'Fabio Carvalho (ACL — long-term)', 'Josh Dasilva (knee — long-term)'],
    awayInjuries: ['Enso Medina (knee — out)'],
    managerNote: null,
    flag: null,
  },
  {
    id: 'bournemouth-man-utd',
    home: 'Bournemouth', homeId: 'bournemouth', homeBadgePlId: 't91', homeColor: '#d71920',
    away: 'Man United',  awayId: 'man-utd',    awayBadgePlId: 't1',  awayColor: '#da291c',
    kickoff: '2026-03-20T20:00:00Z',
    kickoffLabel: 'Fri 20 Mar · 20:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'top5',
    narrative: "Michael Carrick's United arrive at the Vitality in red-hot form — 5 wins in his first 6 league games — desperate to keep pace with Aston Villa in the top-four race. Bournemouth (10th, 41pts) are comfortable but have quietly been one of the draw-heaviest sides in the league, making this a trickier away day than the table suggests.",
    homeInjuries: ['Lewis Cook (thigh — out)', 'Justin Kluivert (knee — out)', 'Ben Doak (hamstring — doubt)'],
    awayInjuries: ['Matthijs de Ligt (back — serious doubt, may miss rest of season)', 'Lisandro Martinez (calf — out)', 'Patrick Dorgu (thigh — out)', 'Noussair Mazraoui (foot — doubt)', 'Mason Mount (knock — doubt)'],
    managerNote: "Michael Carrick (Man Utd) — appointed Jan 13, 2026. Won 5 of his first 6 PL games. Man Utd 3rd, 51pts. Roberto De Zerbi linked for permanent role. Hojlund exit to Napoli (€50m) confirmed — summer funds freed.",
    flag: null,
  },
  {
    id: 'brighton-liverpool',
    home: 'Brighton', homeId: 'brighton', homeBadgePlId: 't36', homeColor: '#0057b8',
    away: 'Liverpool', awayId: 'liverpool', awayBadgePlId: 't14', awayColor: '#c8102e',
    kickoff: '2026-03-21T12:30:00Z',
    kickoffLabel: 'Sat 21 Mar · 12:30 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'top5',
    narrative: "Liverpool head to the Amex needing to bounce back after a difficult run of form — Arne Slot's side are 6th with 48pts and their grip on a European spot is loosening. Brighton have been difficult to beat at home and arrive in decent form after back-to-back league wins. Liverpool with a point to prove is dangerous, but they travel with significant injury concerns.",
    homeInjuries: ['Kaoru Mitoma (ankle — doubt)', 'Adam Webster (knee — out)', 'Tzimas (out)'],
    awayInjuries: ['Alexander Isak (broken leg — season over)', 'Wataru Endo (ankle — out)', 'Conor Bradley (knee — out)', 'Alisson (doubt)', 'Federico Chiesa (doubt)'],
    managerNote: null,
    flag: null,
  },
  {
    id: 'fulham-burnley',
    home: 'Fulham',  homeId: 'fulham',  homeBadgePlId: 't54', homeColor: '#cc0000',
    away: 'Burnley', awayId: 'burnley', awayBadgePlId: 't90', awayColor: '#6c1d45',
    kickoff: '2026-03-21T15:00:00Z',
    kickoffLabel: 'Sat 21 Mar · 15:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'relegation',
    narrative: "Burnley are 19th with 20pts and a goal difference of -26 — a trip to a settled Fulham side could extend their misery. Fulham (12th, 40pts) have been quietly consistent all season and a home win here effectively ends any lingering relegation anxiety while damaging Burnley's survival hopes significantly.",
    homeInjuries: [],
    awayInjuries: ['Squad availability unverified — check closer to kickoff for team news'],
    managerNote: null,
    flag: '⚠️ Burnley injury list not in source data. Assumes near-full squad but verify closer to kickoff.',
  },
  {
    id: 'man-city-crystal-palace',
    home: 'Man City',       homeId: 'man-city',       homeBadgePlId: 't43', homeColor: '#1c86cd',
    away: 'Crystal Palace', awayId: 'crystal-palace', awayBadgePlId: 't31', awayColor: '#1b458f',
    kickoff: '2026-03-21T15:00:00Z',
    kickoffLabel: 'Sat 21 Mar · 15:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'low',
    narrative: "Man City cannot afford dropped points in the title race — Pep Guardiola's side are 2nd (61pts), 9 points behind Arsenal, and must keep winning. Crystal Palace arrive fresh from a stunning 3-1 win at Tottenham last week, but face a very different proposition at the Etihad.",
    homeInjuries: ['Josko Gvardiol (ankle — out)', 'Mateo Kovacic (ankle — out)', 'Rico Lewis (ankle — doubt)'],
    awayInjuries: ['Eddie Nketiah (thigh — out)', 'Cheick Doucoure (knee — out)', 'Daniel Munoz (shoulder — doubt)'],
    managerNote: null,
    flag: '❌ POSTPONED — Man City vs Crystal Palace rescheduled due to Carabao Cup Final (Mar 22). New date TBD by Premier League. DO NOT PUBLISH in GW31 fixture list.',
  },
  {
    id: 'newcastle-sunderland',
    home: 'Newcastle',  homeId: 'newcastle',  homeBadgePlId: 't4',  homeColor: '#241f20',
    away: 'Sunderland', awayId: 'sunderland', awayBadgePlId: 't56', awayColor: '#eb172b',
    kickoff: '2026-03-22T12:00:00Z',
    kickoffLabel: 'Sun 22 Mar · 12:00 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'low',
    awayImportance: 'low',
    narrative: "The Tyne-Wear derby returns to St James' Park for the first time since Sunderland's promotion — the first PL Tyne-Wear derby in over a decade. Newcastle (9th, 42pts) need the points for a European push, while Sunderland's first taste of this fixture in years will be a defining moment for their promoted squad regardless of the result.",
    homeInjuries: ['Bruno Guimaraes (thigh — out until April)', 'Fabian Schär (ankle — out)', 'Lewis Miley (knee — out)', 'Emil Krafth (thigh — out)', 'Jacob Ramsey (suspension — availability for this game unverified)'],
    awayInjuries: ['Bertrand Traore (knee — up to 2 months out)', 'Mundle (thigh — out)', 'Ta Bi (ankle — out)', 'Brian Brobbey (groin — doubt, GW31 status unverified)', 'Dennis Cirkin (thigh — doubt, GW31 status unverified)'],
    managerNote: null,
    flag: null,
  },
  {
    id: 'aston-villa-west-ham',
    home: 'Aston Villa', homeId: 'aston-villa', homeBadgePlId: 't7',  homeColor: '#670e36',
    away: 'West Ham',    awayId: 'west-ham',    awayBadgePlId: 't21', awayColor: '#7a263a',
    kickoff: '2026-03-22T14:15:00Z',
    kickoffLabel: 'Sun 22 Mar · 14:15 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'top5',
    awayImportance: 'relegation',
    narrative: "Aston Villa's top-four place is under real pressure — 4th on 51pts, level on points with Man United — and they must win at Villa Park to maintain their edge. West Ham are in a relegation dog-fight at 17th (29pts), just 1 point above the drop zone. Three points here could prove season-defining for the Hammers. Jadon Sancho returns to availability after being ineligible against parent club Man Utd in GW30.",
    homeInjuries: ['Youri Tielemans (ankle — GW31 status unverified)', 'Boubacar Kamara (knee — GW31 status unverified)', 'Matty Cash (calf — GW31 status unverified)'],
    awayInjuries: ['Crysencio Summerville (lower leg — out, no return timeline)', 'Lukasz Fabianski (back — out)'],
    managerNote: "Jadon Sancho (Villa, on loan from Man United) was ineligible vs Man United in GW30 — returns to full availability for this fixture.",
    flag: null,
  },
  {
    id: 'spurs-nottm-forest',
    home: 'Tottenham',    homeId: 'spurs',        homeBadgePlId: 't6',  homeColor: '#132257',
    away: 'Nottm Forest', awayId: 'nottm-forest', awayBadgePlId: 't17', awayColor: '#dd0000',
    kickoff: '2026-03-22T14:15:00Z',
    kickoffLabel: 'Sun 22 Mar · 14:15 GMT',
    competition: 'Premier League GW31',
    homeImportance: 'relegation',
    awayImportance: 'relegation',
    narrative: "Arguably the biggest six-pointer of the season — two sides staring at the drop meet in a game that could define both their fates. Igor Tudor's Spurs are winless in 5 since his appointment (16th, 29pts), while Vítor Pereira's Forest are 18th (28pts) and already in the relegation zone. Both managers are under extreme pressure. One of them will leave this game with something to hold onto — the other could be looking at a manager change within days.",
    homeInjuries: ['James Maddison (ACL — season over)', 'Joao Palhinha (out)', 'Yves Bissouma (out)', 'Odobert (out)', 'Destiny Udogie (out)', 'Rodrigo Bentancur (out)', 'Mohammed Kudus (out)', 'Lucas Bergvall (out)', 'Dejan Kulusevski (out)', 'Ben Davies (out)', 'Van de Ven & Romero (suspended GW30 — GW31 availability TBC)'],
    awayInjuries: ['Chris Wood (knee — out)', 'Ndoye (out)', 'Willy Boly (knee — out)', 'Filippo Savona (knee — out)', 'John Victor (knee — out)', 'Jair Cunha (ankle — doubt)'],
    managerNote: "Igor Tudor (Spurs) — appointed Feb 14, 0 wins in 5 PL matches. Future in serious doubt. Spurs one point above relegation zone. Vítor Pereira (Forest) — appointed Feb 15, also winless in 5 PL matches since appointment.",
    flag: null,
  },
];
